import {teamPresets,userTeams,saveTeam,teamPresetTotal,teamPresetSummary} from './team-presets.js';
import {CameraRig} from './camera-rig.js';
import {assertPlacementAllowed} from './rules.js';
import {formationData,densityData,expandCounts,planGroup} from './placement.js';
import {armyPresets,mapPresets,armySummary,userArmies,saveArmy} from './presets.js';
import {teamIds,teamData,teamLabel,normalizeMultipliers} from './teams.js';
import {characterData} from './data.js';
import {FieldEditor} from './editor.js';
import {Terrain,terrainData} from './terrain.js';
import {Battle} from './simulation.js';
import {Renderer3D,SpectatorCamera} from './render3d.js';
const $=id=>document.getElementById(id),canvas=$('canvas');let renderer=null,battle=null,selected=null,paused=false,last=0,acc=0,statusTime=0,frameCount=0,simulationMs=0,stepMs=0,renderMs=0;let camera=new SpectatorCamera();const cameraRig=new CameraRig(camera);let teamChoices=[...teamPresets],reportedBattle=null;let placing=false,marker=null;let editing=false,editor=null,editSelected=null,startSnapshot=null;let armies=[...armyPresets],lastPreview=0;
for(let t=0;t<4;t++)$('roster'+t).innerHTML=characterData.map((c,i)=>`<div class="row"><label for="n${t}_${i}">${c.name}<small>HP ${c.hp}${c.immune?'・無敵':''} / 攻撃 ${c.damage.join('+')}${c.specialDamage?' / 特殊 '+c.specialDamage:''}</small></label><input id="n${t}_${i}" type="number" inputmode="numeric" min="0" step="1" value="0" aria-label="チーム${teamData[t].name} ${c.name}の人数"></div>`).join('');
$('placeType').innerHTML=characterData.map((c,i)=>`<option value="${i}">${c.name}</option>`).join('');
function selectedArmy(){return armies.find(a=>a.id===$('armySelect').value)||armies[0];}
function placementTypes(){return $('placeSource').value==='army'?expandCounts(selectedArmy().counts):Array(Number($('placeCount').value)).fill(Number($('placeType').value));}
function placementDescription(){const army=$('placeSource').value==='army',types=placementTypes();return `${teamLabel(Number($('placeTeam').value))} / ${army?selectedArmy().name:characterData[types[0]].name} ${types.length}体 / ${formationData[$('formation').value]} / ${densityData[$('density').value].name}`;}
function syncPlacementUI(){const army=editing&&$('placeSource').value==='army',brush=editing&&$('editTool').value==='brush';$('placeSource').disabled=brush;$('placeTypeLabel').hidden=army&&!brush;$('armyLabel').hidden=!army||brush;$('countLabel').hidden=army||brush;$('armyTotal').hidden=!army||brush;$('armyContents').hidden=!army||brush;$('brushCountLabel').hidden=!brush;
 if(army){$('armyTotal').textContent=`合計 ${selectedArmy().counts.reduce((s,n)=>s+n,0)}体`;$('armyContents').textContent=armySummary(selectedArmy());}
}
function updateArmyList(id=null){const old=id||$('armySelect').value;let message='';try{armies=[...armyPresets,...userArmies()];}catch(e){armies=[...armyPresets];message=e.message;}
 $('armySelect').replaceChildren(...armies.map(a=>{const o=document.createElement('option');o.value=a.id;o.textContent=a.name+'（'+a.counts.reduce((s,n)=>s+n,0)+'体）';return o;}));$('armySelect').value=armies.some(a=>a.id===old)?old:armies[0].id;if(message)$('armySaveStatus').textContent=message;
}
function placementMode(on){placing=on&&!!battle&&!battle.result;marker=null;syncPlacementUI();$('placeOptions').hidden=!placing;$('placeToggle').setAttribute('aria-pressed',String(placing));$('placeToggle').textContent=placing?'配置中':'キャラを追加配置';placementStatus();}
function placementStatus(message=''){const t=Number($('placeTeam').value),c=characterData[Number($('placeType').value)];$('placeStatus').dataset.team=placing?String(t):'';$('placeStatus').textContent=message||(placing?`配置中：TEAM ${teamData[t].name+'（'+teamData[t].label+'）'} / ${c.name} — 地面をタップで連続配置`:'通常操作：ドラッグでカメラを操作');}
$('placeToggle').onclick=()=>placementMode(!placing);$('placeEnd').onclick=()=>placementMode(false);$('placeTeam').onchange=()=>{marker=null;placementStatus();};$('placeType').onchange=()=>{marker=null;placementStatus();};
function groundAt(e){const r=canvas.getBoundingClientRect();camera.update(r.width/r.height);const p=camera.groundPoint(e.clientX-r.left,e.clientY-r.top,r.width,r.height,battle.terrain);return p&&Math.abs(p.x)<49&&Math.abs(p.z)<34?p:null;}
function previewPlacement(e,force=false){if(!force&&editing&&$('editTool').value==='place'&&performance.now()-lastPreview<60)return;if((placing||editing&&['place','terrain','move'].includes($('editTool').value))&&battle&&!battle.result){let p=groundAt(e);marker=p?{...p,team:Number($('placeTeam').value)}:null;
 if(p&&editing&&$('editTool').value==='place'){lastPreview=performance.now();try{const plan=planGroup(editor.stage,placementTypes(),p.x,p.z,$('formation').value,$('density').value);marker.points=plan.units;}catch(error){marker.invalid=true;}}
}}
function config(){return teamIds.map(t=>characterData.map((_,i)=>{let n=Number($(`n${t}_${i}`).value);return Number.isSafeInteger(n)&&n>=0?n:0}));}function totals(){config().forEach((v,t)=>$('total'+t).textContent=`合計 ${v.reduce((a,b)=>a+b,0).toLocaleString()} 人`);}function clear(){document.querySelectorAll('.row input').forEach(e=>e.value=0);totals();}
function demo(){clear();for(let t=0;t<2;t++){for(let [k,n] of [[0,20],[t?1:3,12],[10,8],[t?8:9,3],[18,7]])$(`n${t}_${k}`).value=n;}totals();}demo();document.querySelectorAll('.row input').forEach(e=>e.oninput=totals);$('demo').onclick=demo;$('clear').onclick=clear;
const emptyConfig=()=>teamIds.map(()=>Array(characterData.length).fill(0));
function stageFromBattle(b){return {multipliers:normalizeMultipliers(b.multipliers),units:b.units.map(u=>({id:u.id,team:u.team,type:u.type,x:u.x,z:u.z,yaw:u.yaw})),terrain:JSON.parse(JSON.stringify(b.terrain.objects))};}
function updatePresetList(){try{const names=editor.presets().map(p=>p.name);$('presetList').replaceChildren(...names.map(name=>{const o=document.createElement('option');o.value=name;o.textContent=name;return o;}));$('loadPreset').disabled=!names.length;}catch(e){editing?editorStatus(e.message):placementStatus(e.message);}}
function ensureRenderer(){renderer=renderer||new Renderer3D(canvas);}
function syncMultipliers(){for(const t of teamIds)for(const key of ['hp','attack','speed'])$(`mult${t}_${key}`).value=editor.stage.multipliers?.[t]?.[key]??1;}
function refreshEditor(){syncMultipliers();battle=new Battle(emptyConfig(),editor.snapshot());selected=editSelected?.kind==='unit'?battle.units.find(u=>u.id===editSelected.id):editSelected?{objectId:editSelected.id}:null;marker=null;for(const t of teamIds)$('teamPresetCount'+t).textContent=`現在 ${battle.alive[t]}体`;$('mapName').textContent=mapPresets.find(p=>p.id===editor.stage.mapId)?.name||'カスタム';const counts=editor.counts();$('editCounts').textContent=teamIds.map(t=>`${teamData[t].name}：${battle.alive[t]}体`).join(' / ');$('selected').textContent=editSelected?(editSelected.kind==='unit'?`${characterData[editor.stage.units.find(u=>u.id===editSelected.id)?.type||0].name}を選択中`:`${terrainData[editor.stage.terrain.find(o=>o.id===editSelected.id)?.type]?.name||'地形'}を選択中`):'編集中：タップで配置 / ドラッグ・2本指でカメラ';$('composition').textContent=counts.map((a,t)=>`TEAM ${teamData[t].name}: `+a.map((n,k)=>n?`${characterData[k].name} ${n}`:'').filter(Boolean).join(' / ')+` · 参考総コスト ${a.reduce((s,n,k)=>s+n*characterData[k].cost,0).toLocaleString()}`).join('\n');$('undo').disabled=!editor.history.length;let has=!!selected;$('deleteSelected').hidden=!has;$('rotateSelected').hidden=!has;$('deleteSelected').disabled=!has;$('rotateSelected').disabled=!has;editorStatus();}
function editorStatus(message=''){const tool=$('editTool').value;syncPlacementUI();const labels={place:`${placementDescription()} — 戦場をタップ`,brush:`${teamLabel(Number($('placeTeam').value))} / ${characterData[Number($('placeType').value)].name} ${$('brushCount').value}体ずつ — なぞって配置 / 2本指でカメラ`,select:'選択：キャラ・地形をタップして、移動・削除・回転できます。',move:'移動：選択したものを移す地面をタップ。',terrain:`地形配置：${terrainData[$('terrainType').value]?.name||''} — 地面をタップ`,camera:'カメラのみ：ドラッグ・ピンチで戦場を眺めます。'};$('fieldFeedback').textContent=message;$('fieldFeedback').hidden=!message;$('placeStatus').textContent=message||labels[tool];$('placeStatus').dataset.team=['place','brush'].includes(tool)?$('placeTeam').value:'';$('terrainOptions').hidden=tool!=='terrain';$('terrainScaleLabel').hidden=tool!=='terrain';$('placeOptions').hidden=!['place','brush'].includes(tool);$('placeEnd').hidden=true;}
function openEditor(stage=null){try{cameraRig.release();ensureRenderer();if(stage){editor=editor||new FieldEditor(stage);editor.stage=JSON.parse(JSON.stringify(stage));editor.history=[];editor.stage.multipliers=normalizeMultipliers(stage.multipliers);editor.reindex();}else if(!editor)editor=new FieldEditor(stageFromBattle(new Battle(config())));editing=true;stepMs=0;document.body.classList.add('editing');$('editorBar').after(document.querySelector('.hud'));document.querySelector('.controls').after($('editorDetails'));placing=false;editSelected=null;$('setup').hidden=true;$('battle').hidden=false;$('mapBar').hidden=false;$('teamPresetBar').hidden=false;$('editorBar').hidden=false;$('editorDetails').hidden=false;$('editorPlacement').append($('placeOptions'));$('editorStatus').append($('placeStatus'));$('editorCamera').append($('resetCamera'));$('result').hidden=true;$('placeToggle').hidden=true;$('pause').hidden=true;$('return').hidden=true;$('speed').closest('label').hidden=true;$('clock').textContent='編成';syncMultipliers();refreshEditor();updatePresetList();}catch(e){$('notice').textContent=e.message;}}
async function start(){const stage=stageFromBattle(new Battle(config()));if(editor){stage.mapId=editor.stage.mapId;stage.multipliers=editor.snapshot().multipliers;stage.terrain=editor.snapshot().terrain;let terrain=new Terrain(stage.terrain);for(const u of stage.units)if(!terrain.canOccupy(u.x,u.z,characterData[u.type].radius)){let found=false;for(let r=1;r<25&&!found;r++)for(let a=0;a<16;a++){let x=u.x+Math.cos(a/16*Math.PI*2)*r,z=u.z+Math.sin(a/16*Math.PI*2)*r;if(terrain.canOccupy(x,z,characterData[u.type].radius)){u.x=x;u.z=z;found=true;break;}}if(!found){$('notice').textContent='障害物が多いため自動配置できません。フィールドで地形を減らしてください。';return;}}editor.replace(stage);}else editor=new FieldEditor(stage);if(!editor.stage.units.length){$('notice').textContent='人数を入力して自動配置してください。';return;}openEditor();camera.reset();}
function beginBattle(snapshot=null){let stage=snapshot||editor.snapshot(),counts=teamIds.map(t=>stage.units.filter(u=>u.team===t).length);if(counts.filter(n=>n>0).length<2){editorStatus('2つ以上の陣営にキャラを配置してください。');return;}try{ensureRenderer();cameraRig.release();reportedBattle=null;startSnapshot=JSON.parse(JSON.stringify(stage));battle=new Battle(emptyConfig(),startSnapshot);editing=false;stepMs=0;document.body.classList.remove('editing');editSelected=null;selected=null;paused=false;acc=0;pointers.clear();gesture=null;$('editorBar').hidden=true;$('editorDetails').hidden=true;$('mapBar').hidden=true;$('teamPresetBar').hidden=true;$('fieldFeedback').hidden=true;document.querySelector('.placement').append($('placeOptions'),$('placeStatus'));document.querySelector('.controls').prepend($('resetCamera'));$('result').hidden=true;$('placeToggle').hidden=false;$('placeToggle').disabled=false;$('placeEnd').hidden=false;$('pause').hidden=false;$('return').hidden=false;$('speed').closest('label').hidden=false;$('pause').textContent='一時停止';placementMode(false);$('selected').textContent='棒人間をタップでHP確認';last=performance.now();}catch(e){editorStatus(e.message);}}
function back(){placementMode(false);pointers.clear();gesture=null;openEditor(startSnapshot||editor.snapshot());}
$('quickBack').onclick=()=>openEditor();$('fight').onclick=start;$('editorStart').onclick=()=>beginBattle();$('again').onclick=()=>beginBattle(startSnapshot);$('back').onclick=back;$('return').onclick=back;$('quick').onclick=()=>{$('setup').hidden=false;$('battle').hidden=true;};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'再開':'一時停止';};$('resetCamera').onclick=()=>{cameraRig.release({restore:false});camera.reset();};$('followSelected').onclick=()=>{if(!editing&&cameraRig.follow(selected))updateCameraStatus();};$('freeCamera').onclick=()=>{cameraRig.release();updateCameraStatus();};
$('terrainType').innerHTML=Object.entries(terrainData).map(([key,d])=>`<option value="${key}">${d.name}</option>`).join('');
$('editTool').onchange=()=>{if($('editTool').value==='brush')$('placeSource').value='character';marker=null;editorStatus();};$('terrainType').onchange=()=>editorStatus();$('placeTeam').onchange=()=>{marker=null;editing?editorStatus():placementStatus();};$('placeType').onchange=()=>{marker=null;editing?editorStatus():placementStatus();};
function editAction(fn,message){try{fn();refreshEditor();if(message)editorStatus(message);}catch(e){editorStatus(e.message);}}
$('undo').onclick=()=>editAction(()=>{editor.undo();editSelected=null;},'元に戻しました。');$('deleteSelected').onclick=()=>editAction(()=>{if(editSelected)editor.remove(editSelected.kind,editSelected.id);editSelected=null;},'削除しました。「元に戻す」で戻せます。');$('rotateSelected').onclick=()=>editAction(()=>{if(editSelected)editor.rotate(editSelected.kind,editSelected.id);});
$('clearField').onclick=()=>{const which=$('clearScope').value,name=$('clearScope').selectedOptions[0].textContent;if(confirm(`${name}を削除しますか？ 元に戻すで復元できます。`))editAction(()=>{editor.clear(which);editSelected=null;},'全消去しました。「元に戻す」で戻せます。');};
$('savePreset').onclick=()=>{try{editor.save($('presetName').value);updatePresetList();editorStatus('プリセットを端末に保存しました。');}catch(e){editorStatus(e.message);}};$('loadPreset').onclick=()=>editAction(()=>{editor.load($('presetList').value);syncMultipliers();editSelected=null;},'プリセットを読み込みました。「元に戻す」で前の編成へ戻せます。');
function pick(e){const r=canvas.getBoundingClientRect();let best=null,d=26;for(let u of battle.units){if(u.hp<=0)continue;let q=camera.project(u.x,u.y+1.3,u.z,r.width,r.height);if(q){let dd=Math.hypot(q[0]-(e.clientX-r.left),q[1]-(e.clientY-r.top));if(dd<d){best={kind:'unit',id:u.id};d=dd;}}}if(editing){let p=groundAt(e);for(const o of editor.stage.terrain){let def=terrainData[o.type],radius=(def.radius||def.width/2)*(o.scale||1);let q=camera.project(o.x,battle.terrain.heightAt(o.x,o.z)+(def.blocking?def.height*(o.scale||1)/2:0),o.z,r.width,r.height),dd=q?Math.hypot(q[0]-(e.clientX-r.left),q[1]-(e.clientY-r.top)):Infinity;if(dd<d||(p&&Math.hypot(p.x-o.x,p.z-o.z)<radius&&!best)){best={kind:'terrain',id:o.id};d=Math.min(d,dd);}}}return best;}
function editTap(e){const tool=$('editTool').value,p=groundAt(e);if(tool==='camera')return;if(tool==='select'){editSelected=pick(e);refreshEditor();if(editSelected)editorStatus('選択しました。「移動」「削除」「45°回転」を選べます。');return;}if(!p){editorStatus('戦場の地面をタップしてください。');return;}editAction(()=>{if(tool==='place'){const plan=editor.placeGroup(Number($('placeTeam').value),placementTypes(),p.x,p.z,$('formation').value,$('density').value);queueMicrotask(()=>editorStatus(`${placementDescription()} を配置しました。${plan.adjusted?'障害物や端を避けて陣形を調整しました。':''} 続けてタップできます。`));}else if(tool==='terrain')editor.placeTerrain($('terrainType').value,p.x,p.z,0,Number($('terrainScale').value));else if(tool==='move'){if(!editSelected)throw Error('先に「選択」でキャラ・地形を選んでください。');editor.move(editSelected.kind,editSelected.id,p.x,p.z);}});}
let pointers=new Map(),gesture=null;function state(){let a=[...pointers.values()];return a.length>1?{x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2,d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),n:2}:a.length?{...a[0],n:1}:null;}
function inputMode(){return editing?'edit:'+ $('editTool').value:placing?'place':'camera';}
let brushSession=null;
function brushAt(e){if(!brushSession)return;const pos=groundAt(e);if(!pos)return;const d=brushSession.last?Math.hypot(pos.x-brushSession.last.x,pos.z-brushSession.last.z):Infinity;if(d<2.2)return;
 try{const types=Array(Number($('brushCount').value)).fill(Number($('placeType').value)),plan=planGroup(editor.stage,types,pos.x,pos.z,$('formation').value,$('density').value);assertPlacementAllowed(editor.rules,editor.stage,Number($('placeTeam').value),plan.units);if(!brushSession.started){editor.checkpoint();brushSession.started=true;}
  for(const u of plan.units)editor.stage.units.push({...u,id:editor.nextId++,team:Number($('placeTeam').value),yaw:Number($('placeTeam').value)%2?-Math.PI/2:Math.PI/2});brushSession.last=pos;brushSession.total+=types.length;refreshEditor();editorStatus(`${teamLabel(Number($('placeTeam').value))} / ${characterData[types[0]].name} を${brushSession.total}体追加。1回の「元に戻す」で戻せます。`);
 }catch(error){editorStatus(error.message);}
}
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,button:e.button,moved:false,mode:inputMode()});if(pointers.size>1){for(let p of pointers.values())p.moved=true;marker=null;}else if(e.button===0)previewPlacement(e,true);if(editing&&$('editTool').value==='brush'&&pointers.size===1&&e.button===0)brushSession={started:false,last:null,total:0};gesture=state();};canvas.onpointermove=e=>{let p=pointers.get(e.pointerId);if(!p){previewPlacement(e);return;}p.moved=p.moved||Math.hypot(e.clientX-p.startX,e.clientY-p.startY)>6;p.x=e.clientX;p.y=e.clientY;let next=state();if(editing&&$('editTool').value==='brush'&&next.n===1&&p.button===0&&p.moved&&p.mode===inputMode()){brushAt(e);gesture=next;return;}if(next.n===2)brushSession=null;if(gesture&&next.n===gesture.n&&p.moved){marker=null;if(next.n===2){cameraRig.release({restore:false});camera.pan(next.x-gesture.x,next.y-gesture.y);camera.zoom(gesture.d/Math.max(1,next.d));for(let p of pointers.values())p.moved=true;}else if(p.button===2||e.shiftKey||$('cameraMode').value==='pan'){cameraRig.release({restore:false});camera.pan(next.x-gesture.x,next.y-gesture.y);}else camera.orbit(next.x-gesture.x,next.y-gesture.y);}gesture=next;};
canvas.onpointerup=e=>{let p=pointers.get(e.pointerId);if(p)p.moved=p.moved||Math.hypot(e.clientX-p.startX,e.clientY-p.startY)>6||p.mode!==inputMode();if(p&&p.button===0&&editing&&$('editTool').value==='brush'&&p.mode===inputMode()&&pointers.size===1){if(!p.moved)brushAt(e);brushSession=null;}else if(p&&!p.moved&&p.button===0&&editing){editTap(e);}
else if(p&&!p.moved&&p.button===0&&battle&&placing&&!battle.result){const point=groundAt(e);if(point){try{const u=battle.addCharacter(Number($('placeTeam').value),Number($('placeType').value),point.x,point.z);if(u){marker={...point,team:u.team};placementStatus(`配置中：TEAM ${teamData[u.team].name} / ${u.data.name} を配置しました。続けてタップできます。`);}}catch(error){placementStatus('配置できませんでした。人数を減らして再戦してください。');}}else placementStatus('戦場の地面をタップしてください。');}
else if(p&&!p.moved&&p.button===0&&battle&&!placing){let r=canvas.getBoundingClientRect(),best=null,d=24;for(let u of battle.units){if(u.hp<=0)continue;let q=camera.project(u.x,u.y+1.3,u.z,r.width,r.height);if(q){let dd=Math.hypot(q[0]-(e.clientX-r.left),q[1]-(e.clientY-r.top));if(dd<d){best=u;d=dd;}}}selected=best;}pointers.delete(e.pointerId);gesture=state();};canvas.onpointercancel=e=>{brushSession=null;pointers.delete(e.pointerId);gesture=state();};canvas.addEventListener('wheel',e=>{e.preventDefault();camera.zoom(Math.exp(e.deltaY*.001));},{passive:false});
function ui(){updateCameraStatus();if(editing){if(!editSelected&&['place','brush'].includes($('editTool').value))$('selected').textContent=$('editTool').value==='brush'?`${teamLabel(Number($('placeTeam').value))} / ${characterData[Number($('placeType').value)].name} ${$('brushCount').value}体ずつ — なぞって配置`:placementDescription()+' — 戦場をタップ';for(let t=0;t<4;t++){$('hp'+t).value=battle.initial[t]?1:0;$('stats'+t).textContent=`${battle.alive[t]} 体配置`;}return;}for(let t=0;t<4;t++){$('hp'+t).value=Math.max(0,battle.initial[t]?battle.hp[t]/battle.initial[t]:0);$('stats'+t).textContent=`${battle.alive[t].toLocaleString()} 人 / HP ${Math.ceil(battle.hp[t]).toLocaleString()}`;}let s=Math.floor(battle.time);$('clock').textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;if(selected?.data)$('selected').textContent=`TEAM ${teamData[selected.team].name} · ${selected.data.name} #${selected.id+1} · HP ${Math.ceil(selected.hp)} / ${selected.maxHp}${selected.data.immune?'（無敵）':''}${selected.hp<=0?' · 撃破':''}`;
 let p=battle.projectiles.find(p=>p.kind==='dumbbell'),label=$('dumbbellLabel');label.hidden=!p;if(p){let r=canvas.getBoundingClientRect(),q=camera.project(p.sx+(p.tx-p.sx)*p.time/p.duration,18*(1-p.time/p.duration)+1+battle.terrain.heightAt(p.tx,p.tz),p.sz+(p.tz-p.sz)*p.time/p.duration,r.width,r.height);if(q){label.style.left=q[0]+'px';label.style.top=q[1]+'px';}else label.hidden=true;}
 if(battle.result){showBattleReport();if(placing)placementMode(false);$('placeToggle').disabled=true;$('winner').textContent=battle.result;$('result').hidden=battle.endingTime<2;if(battle.endingTime<2)$('selected').textContent='決着しました。最後の動きを表示中…';}}
function frame(now){let dt=Math.min(.1,(now-last)/1000||0);last=now;if(battle&&!$('battle').hidden){if(renderer.contextLost){paused=true;$('selected').textContent='3D描画が中断しました。ページを再読込してください。';}if(!editing&&battle.result){battle.step(dt);}else if(!editing&&!paused&&!battle.result){acc+=dt*Number($('speed').value);let steps=0,start=performance.now();while(acc>=1/30&&steps<6&&!battle.result){battle.step(1/30);acc-=1/30;steps++;}simulationMs=performance.now()-start;if(steps)stepMs=simulationMs/steps;}if(!editing)cameraRig.update(dt);let drawStart=performance.now();renderer.draw(battle,camera,selected,marker);renderMs=performance.now()-drawStart;ui();statusTime+=dt;frameCount++;if(statusTime>=1){$('performance').textContent=`${battle.count.toLocaleString()} 人編成 · ${Math.round(frameCount/statusTime)} FPS · ${battle.count>1800?'簡略モデル': '3D'}`;$('perfDetail').textContent=`計算 ${stepMs.toFixed(2)} ms / 更新 · 描画準備 ${renderMs.toFixed(2)} ms / フレーム · Draw Call ${renderer.drawCalls} · 描画パーツ ${renderer.parts.toLocaleString()}`;frameCount=0;statusTime=0;}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});

let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false;});$('install').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();const choice=await installPrompt.userChoice;$('install').hidden=true;installPrompt=null;};window.addEventListener('appinstalled',()=>{$('install').hidden=true;installPrompt=null;});

function updateTeamPresetList(selectedId=null){let warning='';try{teamChoices=[...teamPresets,...userTeams()];}catch(e){teamChoices=[...teamPresets];warning=e.message;}
 for(const t of teamIds){const select=$('teamPreset'+t),old=selectedId||select.value;select.replaceChildren(...teamChoices.map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name+'（'+teamPresetTotal(p)+'体）';return o;}));select.value=teamChoices.some(p=>p.id===old)?old:teamChoices[0].id;updateTeamPresetSummary(t);}
 if(warning)$('teamSaveStatus').textContent=warning;
}
function updateTeamPresetSummary(t){const p=teamChoices.find(p=>p.id===$('teamPreset'+t).value)||teamChoices[0];$('teamPresetSummary'+t).textContent=p.description+' / '+teamPresetSummary(p);}
function updateCameraStatus(){$('followSelected').disabled=editing||!selected?.data||selected.hp<=0;$('freeCamera').hidden=cameraRig.mode!=='follow';$('cameraStatus').textContent=cameraRig.mode==='follow'?`追従：${teamLabel(cameraRig.subject.team)} / ${cameraRig.subject.data.name} #${cameraRig.subject.id+1}`:cameraRig.message;}
function showBattleReport(){if(reportedBattle===battle||!battle.report)return;reportedBattle=battle;const report=battle.report;
 $('reportTime').textContent=`戦闘時間 ${report.time.toFixed(1)}秒`;
 $('reportTeams').replaceChildren(...report.teams.map(t=>{const tr=document.createElement('tr');for(const value of [teamLabel(t.team),t.survivors,t.kills,Math.round(t.damage).toLocaleString(),`${t.spawned}（増援${t.reinforcements}）`]){const td=document.createElement('td');td.textContent=value;tr.append(td);}return tr;}));
 const person=r=>r?`${teamLabel(r.team)} / ${characterData[r.type].name} #${r.id+1}${r.alive?'':'（撃破されたキャラ）'}`:'該当なし';$('reportMvp').textContent=`MVP：${person(report.mvp)}${report.mvp?' · '+report.mvp.kills+'撃破':''}`;$('reportDamage').textContent=`最多ダメージ：${person(report.damageLeader)}${report.damageLeader?' · '+Math.round(report.damageLeader.damage).toLocaleString():''}`;
}
updateTeamPresetList();for(const t of teamIds){$('teamPreset'+t).onchange=()=>updateTeamPresetSummary(t);$('applyTeam'+t).onclick=()=>{const p=teamChoices.find(p=>p.id===$('teamPreset'+t).value);if(editor.stage.units.some(u=>u.team===t)&&!confirm(`現在のTEAM ${teamData[t].name}を「${p.name}」に置き換えますか？`))return;editAction(()=>{const result=editor.applyTeamPreset(t,p);editSelected=null;queueMicrotask(()=>editorStatus(`TEAM ${teamData[t].name}を${p.name}（${result.units.length}体）にしました。${result.adjusted?'障害物などを避けて配置を調整しました。':''}「元に戻す」で編成を戻せます。`));});};}
$('saveTeamPreset').onclick=()=>{try{const t=Number($('saveTeamTarget').value),p=saveTeam($('teamPresetName').value,editor.snapshot(),t);updateTeamPresetList(p.id);$('teamSaveStatus').textContent=`TEAM ${teamData[t].name}の配置を「${p.name}」として保存しました。TEAMカードから呼び出せます。`;}catch(e){$('teamSaveStatus').textContent=e.message;}};
$('formation').innerHTML=Object.entries(formationData).map(([id,name])=>`<option value="${id}">${name}</option>`).join('');
$('density').innerHTML=Object.entries(densityData).map(([id,d])=>`<option value="${id}" ${id==='normal'?'selected':''}>${d.name}</option>`).join('');
updateArmyList();
for(const id of ['placeSource','placeCount','formation','density','brushCount'])$(id).onchange=()=>{marker=null;editorStatus();};
$('armySelect').onchange=()=>{const a=selectedArmy();$('formation').value=a.formation;$('density').value=a.density;marker=null;editorStatus();};
$('mapButtons').replaceChildren(...mapPresets.map(p=>{const button=document.createElement('button');button.textContent=p.name;button.title=p.description;button.dataset.map=p.id;button.onclick=()=>{try{const result=editor.applyMap(p.id);editSelected=null;refreshEditor();$('mapHint').textContent=p.description;$('mapChooser').open=false;editorStatus(`${p.name}に変更しました。${result.moved?result.moved+'体の位置を調整しました。':''} 軍団と倍率は保持。「元に戻す」で戻せます。`);}catch(e){editorStatus(e.message);}};return button;}));
$('clearUnits').onclick=()=>editAction(()=>{editor.clearUnits();editSelected=null;},'軍団を全消去しました。地形と倍率は維持。「元に戻す」で戻せます。');
$('armyRows').innerHTML=characterData.map((c,t)=>`<label>${c.name}<input id="armyN${t}" type="number" min="0" max="300" step="1" value="0" inputmode="numeric" aria-label="自作軍団 ${c.name}の人数"></label>`).join('');
function armyDraftCounts(){return characterData.map((_,t)=>Number($('armyN'+t).value));}
function updateCustomTotal(){$('customTotal').textContent=`合計 ${armyDraftCounts().reduce((s,n)=>s+(Number.isFinite(n)?n:0),0)}体`;}for(const t of characterData.keys())$('armyN'+t).oninput=updateCustomTotal;
function fillArmyDraft(counts){counts.forEach((n,t)=>$('armyN'+t).value=n);updateCustomTotal();}
$('armyFromTeam').onclick=()=>{fillArmyDraft(editor.counts()[Number($('placeTeam').value)]);$('armySaveStatus').textContent=teamLabel(Number($('placeTeam').value))+'の構成を読み込みました。';};
$('armyFromPreset').onclick=()=>{const a=selectedArmy();fillArmyDraft(a.counts);$('armyName').value=a.id.startsWith('user-')?a.name:'';$('formation').value=a.formation;$('density').value=a.density;editorStatus();};
$('saveArmy').onclick=()=>{try{const a=saveArmy($('armyName').value,{counts:armyDraftCounts(),formation:$('formation').value,density:$('density').value});updateArmyList(a.id);$('placeSource').value='army';$('editTool').value='place';marker=null;editorStatus('自作軍団を保存しました。戦場をタップして配置できます。');$('armySaveStatus').textContent=a.name+'を保存しました。';}catch(e){$('armySaveStatus').textContent=e.message;}};
openEditor();

for(const t of teamIds)for(const key of ['hp','attack','speed'])$(`mult${t}_${key}`).onchange=()=>{
 try{const values=teamIds.map(t=>Object.fromEntries(['hp','attack','speed'].map(k=>[k,Number($(`mult${t}_${k}`).value)])));const next=normalizeMultipliers(values);editor.checkpoint();editor.stage.multipliers=next;refreshEditor();editorStatus('陣営倍率を更新しました。戦闘開始時に反映されます。');}catch(e){syncMultipliers();editorStatus(e.message);}
};
