import {characterData} from './data.js';
import {FieldEditor} from './editor.js';
import {Terrain,terrainData} from './terrain.js';
import {Battle} from './simulation.js';
import {Renderer3D,SpectatorCamera} from './render3d.js';
const $=id=>document.getElementById(id),canvas=$('canvas');let renderer=null,battle=null,selected=null,paused=false,last=0,acc=0,statusTime=0,frameCount=0,simulationMs=0;let camera=new SpectatorCamera();let placing=false,marker=null;let editing=false,editor=null,editSelected=null,startSnapshot=null;
for(let t=0;t<2;t++)$('roster'+t).innerHTML=characterData.map((c,i)=>`<div class="row"><label for="n${t}_${i}">${c.name}<small>HP ${c.hp}${c.immune?'・無敵':''} / 攻撃 ${c.damage.join('+')}${c.specialDamage?' / 特殊 '+c.specialDamage:''}</small></label><input id="n${t}_${i}" type="number" inputmode="numeric" min="0" step="1" value="0" aria-label="チーム${t?'B':'A'} ${c.name}の人数"></div>`).join('');
$('placeType').innerHTML=characterData.map((c,i)=>`<option value="${i}">${c.name}</option>`).join('');
function placementMode(on){placing=on&&!!battle&&!battle.result;marker=null;$('placeOptions').hidden=!placing;$('placeToggle').setAttribute('aria-pressed',String(placing));$('placeToggle').textContent=placing?'配置中':'キャラを追加配置';placementStatus();}
function placementStatus(message=''){const t=Number($('placeTeam').value),c=characterData[Number($('placeType').value)];$('placeStatus').dataset.team=placing?String(t):'';$('placeStatus').textContent=message||(placing?`配置中：TEAM ${t?'B（赤）':'A（青）'} / ${c.name} — 地面をタップで連続配置`:'通常操作：ドラッグでカメラを操作');}
$('placeToggle').onclick=()=>placementMode(!placing);$('placeEnd').onclick=()=>placementMode(false);$('placeTeam').onchange=()=>{marker=null;placementStatus();};$('placeType').onchange=()=>{marker=null;placementStatus();};
function groundAt(e){const r=canvas.getBoundingClientRect();camera.update(r.width/r.height);const p=camera.groundPoint(e.clientX-r.left,e.clientY-r.top,r.width,r.height,battle.terrain);return p&&Math.abs(p.x)<49&&Math.abs(p.z)<34?p:null;}
function previewPlacement(e){if((placing||editing&&['place','terrain','move'].includes($('editTool').value))&&battle&&!battle.result){let p=groundAt(e);marker=p?{...p,team:Number($('placeTeam').value)}:null;}}
function config(){return [0,1].map(t=>characterData.map((_,i)=>{let n=Number($(`n${t}_${i}`).value);return Number.isSafeInteger(n)&&n>=0?n:0}));}function totals(){config().forEach((v,t)=>$('total'+t).textContent=`合計 ${v.reduce((a,b)=>a+b,0).toLocaleString()} 人`);}function clear(){document.querySelectorAll('.row input').forEach(e=>e.value=0);totals();}
function demo(){clear();for(let t=0;t<2;t++){for(let [k,n] of [[0,20],[t?1:3,12],[10,8],[t?8:9,3],[18,7]])$(`n${t}_${k}`).value=n;}totals();}demo();document.querySelectorAll('.row input').forEach(e=>e.oninput=totals);$('demo').onclick=demo;$('clear').onclick=clear;
const emptyConfig=()=>[Array(characterData.length).fill(0),Array(characterData.length).fill(0)];
function stageFromBattle(b){return {units:b.units.map(u=>({id:u.id,team:u.team,type:u.type,x:u.x,z:u.z,yaw:u.yaw})),terrain:JSON.parse(JSON.stringify(b.terrain.objects))};}
function updatePresetList(){try{const names=editor.presets().map(p=>p.name);$('presetList').replaceChildren(...names.map(name=>{const o=document.createElement('option');o.value=name;o.textContent=name;return o;}));$('loadPreset').disabled=!names.length;}catch(e){editing?editorStatus(e.message):placementStatus(e.message);}}
function ensureRenderer(){renderer=renderer||new Renderer3D(canvas);}
function refreshEditor(){battle=new Battle(emptyConfig(),editor.snapshot());selected=editSelected?.kind==='unit'?battle.units.find(u=>u.id===editSelected.id):editSelected?{objectId:editSelected.id}:null;marker=null;const counts=editor.counts();$('editCounts').textContent=`A：${battle.alive[0]}体 / B：${battle.alive[1]}体`;$('selected').textContent=editSelected?(editSelected.kind==='unit'?`${characterData[editor.stage.units.find(u=>u.id===editSelected.id)?.type||0].name}を選択中`:`${terrainData[editor.stage.terrain.find(o=>o.id===editSelected.id)?.type]?.name||'地形'}を選択中`):'編集中：タップで配置 / ドラッグ・2本指でカメラ';$('composition').textContent=counts.map((a,t)=>`TEAM ${t?'B':'A'}: `+a.map((n,k)=>n?`${characterData[k].name} ${n}`:'').filter(Boolean).join(' / ')).join('\n');$('undo').disabled=!editor.history.length;let has=!!selected;$('deleteSelected').hidden=!has;$('rotateSelected').hidden=!has;$('deleteSelected').disabled=!has;$('rotateSelected').disabled=!has;editorStatus();}
function editorStatus(message=''){const tool=$('editTool').value;const labels={place:`キャラ配置：TEAM ${Number($('placeTeam').value)?'B（赤）':'A（青）'} / ${characterData[Number($('placeType').value)].name} — 地面をタップ`,select:'選択：キャラ・地形をタップして、移動・削除・回転できます。',move:'移動：選択したものを移す地面をタップ。',terrain:`地形配置：${terrainData[$('terrainType').value]?.name||''} — 地面をタップ`,camera:'カメラのみ：ドラッグ・ピンチで戦場を眺めます。'};$('placeStatus').textContent=message||labels[tool];$('placeStatus').dataset.team=tool==='place'?$('placeTeam').value:'';$('terrainOptions').hidden=tool!=='terrain';$('terrainScaleLabel').hidden=tool!=='terrain';$('placeOptions').hidden=tool!=='place';$('placeEnd').hidden=true;}
function openEditor(stage=null){try{ensureRenderer();if(stage){editor=editor||new FieldEditor(stage);editor.stage=JSON.parse(JSON.stringify(stage));editor.history=[];editor.reindex();}else if(!editor)editor=new FieldEditor(stageFromBattle(new Battle(config())));editing=true;document.body.classList.add('editing');$('editorBar').after(document.querySelector('.hud'));document.querySelector('.controls').after($('editorDetails'));placing=false;editSelected=null;$('setup').hidden=true;$('battle').hidden=false;$('editorBar').hidden=false;$('editorDetails').hidden=false;$('editorPlacement').append($('placeOptions'));$('editorStatus').append($('placeStatus'));$('editorCamera').append($('resetCamera'));$('result').hidden=true;$('placeToggle').hidden=true;$('pause').hidden=true;$('return').hidden=true;$('speed').closest('label').hidden=true;$('clock').textContent='編成';refreshEditor();updatePresetList();}catch(e){$('notice').textContent=e.message;}}
async function start(){const stage=stageFromBattle(new Battle(config()));if(editor){stage.terrain=editor.snapshot().terrain;let terrain=new Terrain(stage.terrain);for(const u of stage.units)if(!terrain.canOccupy(u.x,u.z,characterData[u.type].radius)){let found=false;for(let r=1;r<25&&!found;r++)for(let a=0;a<16;a++){let x=u.x+Math.cos(a/16*Math.PI*2)*r,z=u.z+Math.sin(a/16*Math.PI*2)*r;if(terrain.canOccupy(x,z,characterData[u.type].radius)){u.x=x;u.z=z;found=true;break;}}if(!found){$('notice').textContent='障害物が多いため自動配置できません。フィールドで地形を減らしてください。';return;}}editor.replace(stage);}else editor=new FieldEditor(stage);if(!editor.stage.units.length){$('notice').textContent='人数を入力して自動配置してください。';return;}openEditor();camera.reset();}
function beginBattle(snapshot=null){let stage=snapshot||editor.snapshot(),counts=[0,1].map(t=>stage.units.filter(u=>u.team===t).length);if(counts.some(n=>!n)){editorStatus(`TEAM ${counts[0]?'B':'A'}にキャラを配置してください。`);return;}try{ensureRenderer();startSnapshot=JSON.parse(JSON.stringify(stage));battle=new Battle(emptyConfig(),startSnapshot);editing=false;document.body.classList.remove('editing');editSelected=null;selected=null;paused=false;acc=0;pointers.clear();gesture=null;$('editorBar').hidden=true;$('editorDetails').hidden=true;document.querySelector('.placement').append($('placeOptions'),$('placeStatus'));document.querySelector('.controls').prepend($('resetCamera'));$('result').hidden=true;$('placeToggle').hidden=false;$('placeToggle').disabled=false;$('placeEnd').hidden=false;$('pause').hidden=false;$('return').hidden=false;$('speed').closest('label').hidden=false;$('pause').textContent='一時停止';placementMode(false);$('selected').textContent='棒人間をタップでHP確認';last=performance.now();}catch(e){editorStatus(e.message);}}
function back(){placementMode(false);pointers.clear();gesture=null;openEditor(startSnapshot||editor.snapshot());}
$('quickBack').onclick=()=>openEditor();$('fight').onclick=start;$('editorStart').onclick=()=>beginBattle();$('again').onclick=()=>beginBattle(startSnapshot);$('back').onclick=back;$('return').onclick=back;$('quick').onclick=()=>{$('setup').hidden=false;$('battle').hidden=true;};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'再開':'一時停止';};$('resetCamera').onclick=()=>camera.reset();
$('terrainType').innerHTML=Object.entries(terrainData).map(([key,d])=>`<option value="${key}">${d.name}</option>`).join('');
$('editTool').onchange=()=>{marker=null;editorStatus();};$('terrainType').onchange=()=>editorStatus();$('placeTeam').onchange=()=>{marker=null;editing?editorStatus():placementStatus();};$('placeType').onchange=()=>{marker=null;editing?editorStatus():placementStatus();};
function editAction(fn,message){try{fn();refreshEditor();if(message)editorStatus(message);}catch(e){editorStatus(e.message);}}
$('undo').onclick=()=>editAction(()=>{editor.undo();editSelected=null;},'元に戻しました。');$('deleteSelected').onclick=()=>editAction(()=>{if(editSelected)editor.remove(editSelected.kind,editSelected.id);editSelected=null;},'削除しました。「元に戻す」で戻せます。');$('rotateSelected').onclick=()=>editAction(()=>{if(editSelected)editor.rotate(editSelected.kind,editSelected.id);});
$('clearField').onclick=()=>{const which=$('clearScope').value,name=$('clearScope').selectedOptions[0].textContent;if(confirm(`${name}を削除しますか？ 元に戻すで復元できます。`))editAction(()=>{editor.clear(which);editSelected=null;},'全消去しました。「元に戻す」で戻せます。');};
$('savePreset').onclick=()=>{try{editor.save($('presetName').value);updatePresetList();editorStatus('プリセットを端末に保存しました。');}catch(e){editorStatus(e.message);}};$('loadPreset').onclick=()=>editAction(()=>{editor.load($('presetList').value);editSelected=null;},'プリセットを読み込みました。「元に戻す」で前の編成へ戻せます。');
function pick(e){const r=canvas.getBoundingClientRect();let best=null,d=26;for(let u of battle.units){if(u.hp<=0)continue;let q=camera.project(u.x,u.y+1.3,u.z,r.width,r.height);if(q){let dd=Math.hypot(q[0]-(e.clientX-r.left),q[1]-(e.clientY-r.top));if(dd<d){best={kind:'unit',id:u.id};d=dd;}}}if(editing){let p=groundAt(e);for(const o of editor.stage.terrain){let def=terrainData[o.type],radius=(def.radius||def.width/2)*(o.scale||1);let q=camera.project(o.x,battle.terrain.heightAt(o.x,o.z)+(def.blocking?def.height*(o.scale||1)/2:0),o.z,r.width,r.height),dd=q?Math.hypot(q[0]-(e.clientX-r.left),q[1]-(e.clientY-r.top)):Infinity;if(dd<d||(p&&Math.hypot(p.x-o.x,p.z-o.z)<radius&&!best)){best={kind:'terrain',id:o.id};d=Math.min(d,dd);}}}return best;}
function editTap(e){const tool=$('editTool').value,p=groundAt(e);if(tool==='camera')return;if(tool==='select'){editSelected=pick(e);refreshEditor();if(editSelected)editorStatus('選択しました。「移動」「削除」「45°回転」を選べます。');return;}if(!p){editorStatus('戦場の地面をタップしてください。');return;}editAction(()=>{if(tool==='place')editor.placeUnit(Number($('placeTeam').value),Number($('placeType').value),p.x,p.z);else if(tool==='terrain')editor.placeTerrain($('terrainType').value,p.x,p.z,0,Number($('terrainScale').value));else if(tool==='move'){if(!editSelected)throw Error('先に「選択」でキャラ・地形を選んでください。');editor.move(editSelected.kind,editSelected.id,p.x,p.z);}});}
let pointers=new Map(),gesture=null;function state(){let a=[...pointers.values()];return a.length>1?{x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2,d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),n:2}:a.length?{...a[0],n:1}:null;}
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,button:e.button,moved:false});if(pointers.size>1){for(let p of pointers.values())p.moved=true;marker=null;}else previewPlacement(e);gesture=state();};canvas.onpointermove=e=>{let p=pointers.get(e.pointerId);if(!p){previewPlacement(e);return;}p.moved=p.moved||Math.hypot(e.clientX-p.startX,e.clientY-p.startY)>6;p.x=e.clientX;p.y=e.clientY;let next=state();if(gesture&&next.n===gesture.n&&p.moved){marker=null;if(next.n===2){camera.pan(next.x-gesture.x,next.y-gesture.y);camera.zoom(gesture.d/Math.max(1,next.d));for(let p of pointers.values())p.moved=true;}else if(p.button===2||e.shiftKey||$('cameraMode').value==='pan')camera.pan(next.x-gesture.x,next.y-gesture.y);else camera.orbit(next.x-gesture.x,next.y-gesture.y);}gesture=next;};
canvas.onpointerup=e=>{let p=pointers.get(e.pointerId);if(p&&!p.moved&&p.button===0&&editing){editTap(e);}
else if(p&&!p.moved&&p.button===0&&battle&&placing&&!battle.result){const point=groundAt(e);if(point){try{const u=battle.addCharacter(Number($('placeTeam').value),Number($('placeType').value),point.x,point.z);if(u){marker={...point,team:u.team};placementStatus(`配置中：TEAM ${u.team?'B（赤）':'A（青）'} / ${u.data.name} を配置しました。続けてタップできます。`);}}catch(error){placementStatus('配置できませんでした。人数を減らして再戦してください。');}}else placementStatus('戦場の地面をタップしてください。');}
else if(p&&!p.moved&&p.button===0&&battle&&!placing){let r=canvas.getBoundingClientRect(),best=null,d=24;for(let u of battle.units){if(u.hp<=0)continue;let q=camera.project(u.x,u.y+1.3,u.z,r.width,r.height);if(q){let dd=Math.hypot(q[0]-(e.clientX-r.left),q[1]-(e.clientY-r.top));if(dd<d){best=u;d=dd;}}}selected=best;}pointers.delete(e.pointerId);gesture=state();};canvas.onpointercancel=e=>{pointers.delete(e.pointerId);gesture=state();};canvas.addEventListener('wheel',e=>{e.preventDefault();camera.zoom(Math.exp(e.deltaY*.001));},{passive:false});
function ui(){if(editing){for(let t=0;t<2;t++){$('hp'+t).value=battle.initial[t]?1:0;$('stats'+t).textContent=`${battle.alive[t]} 体配置`;}return;}for(let t=0;t<2;t++){$('hp'+t).value=Math.max(0,battle.hp[t]/battle.initial[t]);$('stats'+t).textContent=`${battle.alive[t].toLocaleString()} 人 / HP ${Math.ceil(battle.hp[t]).toLocaleString()}`;}let s=Math.floor(battle.time);$('clock').textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;if(selected?.data)$('selected').textContent=`TEAM ${selected.team?'B':'A'} · ${selected.data.name} #${selected.id+1} · HP ${Math.ceil(selected.hp)} / ${selected.data.hp}${selected.data.immune?'（無敵）':''}${selected.hp<=0?' · 撃破':''}`;
 let p=battle.projectiles.find(p=>p.kind==='dumbbell'),label=$('dumbbellLabel');label.hidden=!p;if(p){let r=canvas.getBoundingClientRect(),q=camera.project(p.sx+(p.tx-p.sx)*p.time/p.duration,18*(1-p.time/p.duration)+1+battle.terrain.heightAt(p.tx,p.tz),p.sz+(p.tz-p.sz)*p.time/p.duration,r.width,r.height);if(q){label.style.left=q[0]+'px';label.style.top=q[1]+'px';}else label.hidden=true;}
 if(battle.result){if(placing)placementMode(false);$('placeToggle').disabled=true;$('winner').textContent=battle.result;$('result').hidden=battle.endingTime<2;if(battle.endingTime<2)$('selected').textContent='決着しました。最後の動きを表示中…';}}
function frame(now){let dt=Math.min(.1,(now-last)/1000||0);last=now;if(battle&&!$('battle').hidden){if(renderer.contextLost){paused=true;$('selected').textContent='3D描画が中断しました。ページを再読込してください。';}if(!editing&&battle.result){battle.step(dt);}else if(!editing&&!paused&&!battle.result){acc+=dt*Number($('speed').value);let steps=0,start=performance.now();while(acc>=1/30&&steps<6&&!battle.result){battle.step(1/30);acc-=1/30;steps++;}simulationMs=performance.now()-start;}renderer.draw(battle,camera,selected,marker);ui();statusTime+=dt;frameCount++;if(statusTime>=1){$('performance').textContent=`${battle.count.toLocaleString()} 人編成 · ${Math.round(frameCount/statusTime)} FPS · ${battle.count>1800?'簡略モデル': '3D'}`;frameCount=0;statusTime=0;}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});

let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false;});$('install').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();const choice=await installPrompt.userChoice;$('install').hidden=true;installPrompt=null;};window.addEventListener('appinstalled',()=>{$('install').hidden=true;installPrompt=null;});

openEditor();
