import {characterData} from './data.js';
import {Battle} from './simulation.js';
import {Renderer3D,SpectatorCamera} from './render3d.js';
const $=id=>document.getElementById(id),canvas=$('canvas');let renderer=null,battle=null,selected=null,paused=false,last=0,acc=0,statusTime=0,frameCount=0,simulationMs=0;let camera=new SpectatorCamera();let placing=false,marker=null;
for(let t=0;t<2;t++)$('roster'+t).innerHTML=characterData.map((c,i)=>`<div class="row"><label for="n${t}_${i}">${c.name}<small>HP ${c.hp}${c.immune?'・無敵':''} / 攻撃 ${c.damage.join('+')}${c.specialDamage?' / 特殊 '+c.specialDamage:''}</small></label><input id="n${t}_${i}" type="number" inputmode="numeric" min="0" step="1" value="0" aria-label="チーム${t?'B':'A'} ${c.name}の人数"></div>`).join('');
$('placeType').innerHTML=characterData.map((c,i)=>`<option value="${i}">${c.name}</option>`).join('');
function placementMode(on){placing=on&&!!battle&&!battle.result;marker=null;$('placeOptions').hidden=!placing;$('placeToggle').setAttribute('aria-pressed',String(placing));$('placeToggle').textContent=placing?'配置中':'キャラを追加配置';placementStatus();}
function placementStatus(message=''){const t=Number($('placeTeam').value),c=characterData[Number($('placeType').value)];$('placeStatus').dataset.team=placing?String(t):'';$('placeStatus').textContent=message||(placing?`配置中：TEAM ${t?'B（赤）':'A（青）'} / ${c.name} — 地面をタップで連続配置`:'通常操作：ドラッグでカメラを操作');}
$('placeToggle').onclick=()=>placementMode(!placing);$('placeEnd').onclick=()=>placementMode(false);$('placeTeam').onchange=()=>{marker=null;placementStatus();};$('placeType').onchange=()=>{marker=null;placementStatus();};
function groundAt(e){const r=canvas.getBoundingClientRect();camera.update(r.width/r.height);const p=camera.groundPoint(e.clientX-r.left,e.clientY-r.top,r.width,r.height);return p&&battle.terrain.canOccupy(p.x,p.z,characterData[Number($('placeType').value)].radius)?p:null;}
function previewPlacement(e){if(placing&&battle&&!battle.result){let p=groundAt(e);marker=p?{...p,team:Number($('placeTeam').value)}:null;}}
function config(){return [0,1].map(t=>characterData.map((_,i)=>{let n=Number($(`n${t}_${i}`).value);return Number.isSafeInteger(n)&&n>=0?n:0}));}function totals(){config().forEach((v,t)=>$('total'+t).textContent=`合計 ${v.reduce((a,b)=>a+b,0).toLocaleString()} 人`);}function clear(){document.querySelectorAll('input').forEach(e=>e.value=0);totals();}
function demo(){clear();for(let t=0;t<2;t++){for(let [k,n] of [[0,20],[t?1:3,12],[10,8],[t?8:9,3],[18,7]])$(`n${t}_${k}`).value=n;}totals();}demo();document.querySelectorAll('input').forEach(e=>e.oninput=totals);$('demo').onclick=demo;$('clear').onclick=clear;
async function start(){let conf=config();if(!conf.every(a=>a.some(n=>n>0))){$('notice').textContent='両チームに1人以上設定してください。';return;}$('fight').disabled=true;await new Promise(r=>setTimeout(r,20));try{renderer=renderer||new Renderer3D(canvas);battle=new Battle(conf);}catch(e){$('notice').textContent=e.message||'人数を減らしてもう一度お試しください。';$('fight').disabled=false;return;}$('fight').disabled=false;$('setup').hidden=true;$('battle').hidden=false;$('result').hidden=true;$('placeToggle').disabled=false;selected=null;paused=false;acc=0;camera.reset();placementMode(false);pointers.clear();gesture=null;$('pause').textContent='一時停止';$('selected').textContent='棒人間をタップでHP確認';last=performance.now();}
function back(){placementMode(false);pointers.clear();gesture=null;battle=null;$('setup').hidden=false;$('battle').hidden=true;}$('fight').onclick=start;$('again').onclick=start;$('back').onclick=back;$('return').onclick=back;$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'再開':'一時停止';};$('resetCamera').onclick=()=>camera.reset();$('cameraMode').onchange=()=>{};
let pointers=new Map(),gesture=null;function state(){let a=[...pointers.values()];return a.length>1?{x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2,d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),n:2}:a.length?{...a[0],n:1}:null;}
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,button:e.button,moved:false});if(pointers.size>1){for(let p of pointers.values())p.moved=true;marker=null;}else previewPlacement(e);gesture=state();};canvas.onpointermove=e=>{let p=pointers.get(e.pointerId);if(!p){previewPlacement(e);return;}p.moved=p.moved||Math.hypot(e.clientX-p.startX,e.clientY-p.startY)>6;p.x=e.clientX;p.y=e.clientY;let next=state();if(gesture&&next.n===gesture.n&&p.moved){marker=null;if(next.n===2){camera.pan(next.x-gesture.x,next.y-gesture.y);camera.zoom(gesture.d/Math.max(1,next.d));for(let p of pointers.values())p.moved=true;}else if(p.button===2||e.shiftKey||$('cameraMode').value==='pan')camera.pan(next.x-gesture.x,next.y-gesture.y);else camera.orbit(next.x-gesture.x,next.y-gesture.y);}gesture=next;};
canvas.onpointerup=e=>{let p=pointers.get(e.pointerId);if(p&&!p.moved&&p.button===0&&battle&&placing&&!battle.result){const point=groundAt(e);if(point){try{const u=battle.addCharacter(Number($('placeTeam').value),Number($('placeType').value),point.x,point.z);if(u){marker={...point,team:u.team};placementStatus(`配置中：TEAM ${u.team?'B（赤）':'A（青）'} / ${u.data.name} を配置しました。続けてタップできます。`);}}catch(error){placementStatus('配置できませんでした。人数を減らして再戦してください。');}}else placementStatus('戦場の地面をタップしてください。');}
else if(p&&!p.moved&&p.button===0&&battle&&!placing){let r=canvas.getBoundingClientRect(),best=null,d=24;for(let u of battle.units){if(u.hp<=0)continue;let q=camera.project(u.x,u.y+1.3,u.z,r.width,r.height);if(q){let dd=Math.hypot(q[0]-(e.clientX-r.left),q[1]-(e.clientY-r.top));if(dd<d){best=u;d=dd;}}}selected=best;}pointers.delete(e.pointerId);gesture=state();};canvas.onpointercancel=e=>{pointers.delete(e.pointerId);gesture=state();};canvas.addEventListener('wheel',e=>{e.preventDefault();camera.zoom(Math.exp(e.deltaY*.001));},{passive:false});
function ui(){for(let t=0;t<2;t++){$('hp'+t).value=Math.max(0,battle.hp[t]/battle.initial[t]);$('stats'+t).textContent=`${battle.alive[t].toLocaleString()} 人 / HP ${Math.ceil(battle.hp[t]).toLocaleString()}`;}let s=Math.floor(battle.time);$('clock').textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;if(selected)$('selected').textContent=`TEAM ${selected.team?'B':'A'} · ${selected.data.name} #${selected.id+1} · HP ${Math.ceil(selected.hp)} / ${selected.data.hp}${selected.data.immune?'（無敵）':''}${selected.hp<=0?' · 撃破':''}`;
 let p=battle.projectiles.find(p=>p.kind==='dumbbell'),label=$('dumbbellLabel');label.hidden=!p;if(p){let r=canvas.getBoundingClientRect(),q=camera.project(p.sx+(p.tx-p.sx)*p.time/p.duration,18*(1-p.time/p.duration)+1,p.sz+(p.tz-p.sz)*p.time/p.duration,r.width,r.height);if(q){label.style.left=q[0]+'px';label.style.top=q[1]+'px';}else label.hidden=true;}
 if(battle.result){if(placing)placementMode(false);$('placeToggle').disabled=true;$('winner').textContent=battle.result;$('result').hidden=false;}}
function frame(now){let dt=Math.min(.1,(now-last)/1000||0);last=now;if(battle){if(renderer.contextLost){paused=true;$('selected').textContent='3D描画が中断しました。ページを再読込してください。';}if(!paused&&!battle.result){acc+=dt*Number($('speed').value);let steps=0,start=performance.now();while(acc>=1/30&&steps<6){battle.step(1/30);acc-=1/30;steps++;}simulationMs=performance.now()-start;}renderer.draw(battle,camera,selected,marker);ui();statusTime+=dt;frameCount++;if(statusTime>=1){$('performance').textContent=`${battle.count.toLocaleString()} 人編成 · ${Math.round(frameCount/statusTime)} FPS · ${battle.count>1800?'簡略モデル': '3D'}`;frameCount=0;statusTime=0;}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});

let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false;});$('install').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();const choice=await installPrompt.userChoice;$('install').hidden=true;installPrompt=null;};window.addEventListener('appinstalled',()=>{$('install').hidden=true;installPrompt=null;});
