import assert from 'node:assert/strict';import fs from 'node:fs';import {FieldEditor} from '../editor.js';import {Battle} from '../simulation.js';import {characterData} from '../data.js';import {planGroup,formationData,densityData,expandCounts} from '../placement.js';import {armyPresets,mapPresets,saveArmy,userArmies} from '../presets.js';import {Terrain} from '../terrain.js';
globalThis.localStorage={data:new Map(),getItem(k){return this.data.get(k)??null},setItem(k,v){this.data.set(k,v)}};let checks=[],timings=[];const ok=(v,s)=>{assert(v,s);checks.push(s)};
function verify(stage){const terrain=new Terrain(stage.terrain),ids=stage.units.map(u=>u.id);assert.equal(new Set(ids).size,ids.length);for(const u of stage.units)assert(terrain.canOccupy(u.x,u.z,characterData[u.type].radius));for(let i=0;i<stage.units.length;i++)for(let j=0;j<i;j++){const u=stage.units[i],v=stage.units[j];assert(Math.hypot(u.x-v.x,u.z-v.z)>=characterData[u.type].radius+characterData[v.type].radius+.08-1e-6,'overlap');}}
for(const n of [1,5,10,25,50,100])for(const formation of Object.keys(formationData))for(const density of Object.keys(densityData)){const e=new FieldEditor();let start=performance.now();e.placeGroup(0,Array(n).fill(0),0,0,formation,density);timings.push({n,formation,density,ms:performance.now()-start});assert.equal(e.stage.units.length,n);verify(e.stage);assert.equal(e.history.length,1);e.undo();assert.equal(e.stage.units.length,0);}checks.push('all 144 count/formation/density combinations; no overlap; atomic undo');
for(const [x,z] of [[48,33],[-48,-33],[0,33]])for(const formation of ['row','column','circle','scatter']){const e=new FieldEditor();e.placeGroup(3,Array(100).fill(0),x,z,formation,'wide');verify(e.stage);}checks.push('100-unit edge placement: all formations stay in field');
for(const map of mapPresets){for(const army of armyPresets){const e=new FieldEditor();e.applyMap(map.id);e.placeGroup(2,expandCounts(army.counts),-20,0,army.formation,army.density);assert.equal(e.stage.units.length,army.counts.reduce((s,n)=>s+n,0));verify(e.stage);}}checks.push('all 12 army presets × all 6 maps; exact counts and no overlap');
let e=new FieldEditor();for(let t=0;t<4;t++)e.placeGroup(t,Array(50).fill(0),t%2?20:-20,t<2?-15:15);ok(e.counts().every(a=>a[0]===50),'all four teams: 50 each');verify(e.stage);
const original=e.snapshot();for(const map of mapPresets){e.applyMap(map.id);verify(e.stage);ok(e.stage.units.length===200,'map '+map.id+' preserves all troops');e.undo();assert.deepEqual(e.stage,original);}checks.push('map one undo restores exact original');
e.stage.multipliers[2]={hp:2,attack:3,speed:2};e.save('phase2');let loaded=new FieldEditor();loaded.load('phase2');assert.deepEqual(loaded.stage,e.stage);checks.push('full field save/load: four armies and multipliers');
let counts=characterData.map((_,i)=>i===0?40:i===19?2:0);let army=saveArmy('自作<軍>',{counts,formation:'circle',density:'wide'});assert.equal(userArmies().length,1);saveArmy('自作<軍>',{counts,formation:'v',density:'close'});assert.equal(userArmies().length,1);assert.equal(userArmies()[0].formation,'v');checks.push('custom army save/update/reload includes counts, formation, density');
const before=e.snapshot(),history=e.history.length;assert.throws(()=>e.placeGroup(4,[0],0,0));assert.throws(()=>e.placeGroup(0,[],0,0));assert.throws(()=>e.placeGroup(0,Array(301).fill(0),0,0));assert.throws(()=>e.placeGroup(0,[999],0,0));assert.throws(()=>e.placeGroup(0,[0],Infinity,0));assert.deepEqual(e.stage,before);assert.equal(e.history.length,history);checks.push('invalid group atomic: no changes/history');
const blocked={units:[],terrain:Array.from({length:17},(_,i)=>[-30,0,30].map((x,j)=>({id:i*3+j,type:'wall',x,z:-32+i*4,yaw:0,scale:3}))).flat()};const block=new FieldEditor(blocked);const blockBefore=block.snapshot();assert.throws(()=>block.placeGroup(0,Array(100).fill(19),0,0));assert.deepEqual(block.stage,blockBefore);assert.equal(block.history.length,0);checks.push('insufficient space rejects full batch without partial placement');
e=new FieldEditor();for(let t=0;t<2;t++)for(let i=0;i<3;i++)e.placeGroup(t,Array(100).fill(0),t?20:-20,(i-1)*18);verify(e.stage);let b=new Battle([],e.snapshot()),start=performance.now();for(let i=0;i<1800&&!b.result;i++)b.step(1/30);ok(b.events>0,'300vs300 stamp-built battle attacks');ok(b.units.every(u=>[u.x,u.z,u.hp].every(Number.isFinite)),'300vs300 valid state');let combatMs=performance.now()-start;
e=new FieldEditor();for(let t=0;t<4;t++)e.placeGroup(t,expandCounts(armyPresets[t===3?10:t].counts),t%2?20:-20,t<2?-15:15);b=new Battle([],e.snapshot());for(let i=0;i<900&&!b.result;i++)b.step(1/30);ok(b.events>0&&b.units.every(u=>Number.isFinite(u.hp)),'four-way mixed armies including gigant battle');
const result={checks,placement:{tests:timings.length,meanMs:timings.reduce((s,t)=>s+t.ms,0)/timings.length,maxMs:Math.max(...timings.map(t=>t.ms)),hundredMeanMs:timings.filter(t=>t.n===100).reduce((s,t)=>s+t.ms,0)/24},combatMs};fs.writeFileSync('phase2-logic-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
