import assert from 'node:assert/strict';import fs from 'node:fs';import {Battle} from '../simulation.js';import {Battle as OldBattle} from './baseline-v8/simulation.js';import {characterData} from '../data.js';import {characterData as oldData} from './baseline-v8/data.js';import {FieldEditor} from '../editor.js';import {teamPresets,teamPresetTotal,userTeams,saveTeam} from '../team-presets.js';import {armyPresets,mapPresets} from '../presets.js';import {expandCounts} from '../placement.js';import {CameraRig} from '../camera-rig.js';import {SpectatorCamera} from '../render3d.js';import {GameMode,BattleRules,SandboxMode} from '../rules.js';import {Terrain} from '../terrain.js';
globalThis.localStorage={data:new Map(),getItem(k){return this.data.get(k)??null},setItem(k,v){this.data.set(k,v)}};let checks=[];function ok(v,s){assert(v,s);checks.push(s);}function verify(stage){const terrain=new Terrain(stage.terrain);assert.equal(new Set(stage.units.map(u=>u.id)).size,stage.units.length);for(const u of stage.units)assert(terrain.canOccupy(u.x,u.z,characterData[u.type].radius));for(let i=0;i<stage.units.length;i++)for(let j=0;j<i;j++){const u=stage.units[i],v=stage.units[j];assert(Math.hypot(u.x-v.x,u.z-v.z)>=characterData[u.type].radius+characterData[v.type].radius+.08-1e-6);}}
for(let i=0;i<characterData.length;i++){const {cost,role,...data}=characterData[i];assert.deepEqual(data,oldData[i]);assert(cost>0&&role);}ok(characterData[0].cost<characterData[18].cost&&characterData[18].cost<characterData[19].cost&&characterData[19].cost<characterData[17].cost,'only cost/role added; all combat stats preserved');
for(const map of mapPresets)for(const preset of teamPresets)for(let t=0;t<4;t++){const e=new FieldEditor();e.applyMap(map.id);e.applyTeamPreset(t,preset);assert.equal(e.stage.units.length,teamPresetTotal(preset));verify(e.stage);}checks.push('6 maps × 6 team presets × 4 teams = 144 placement cases');
let e=new FieldEditor();e.stage.multipliers[2]={hp:2,attack:3,speed:2};e.applyMap('castle');e.placeGroup(0,expandCounts(armyPresets[0].counts),-24,-14);e.placeGroup(1,expandCounts(armyPresets[10].counts),24,-14);let before=e.snapshot();e.applyTeamPreset(2,teamPresets[0]);ok(e.stage.units.filter(u=>u.team===2).length===52,'TEAM C preset exact count');assert.deepEqual(e.stage.units.filter(u=>u.team!==2),before.units);assert.deepEqual(e.stage.terrain,before.terrain);assert.deepEqual(e.stage.multipliers,before.multipliers);e.undo();assert.deepEqual(e.stage,before);checks.push('only target TEAM replaced; terrain/multipliers/other armies and atomic undo preserved');
e.applyTeamPreset(0,teamPresets[5]);e.placeGroup(0,[0,3],-35,-25,'row','wide');before=e.snapshot();let custom=saveTeam('自作<チーム>',e.stage,0);saveTeam('自作<チーム>',e.stage,0);ok(userTeams().length===1,'custom team same-name update');for(const t of [0,1,2,3]){let target=new FieldEditor();target.applyTeamPreset(t,custom);verify(target.stage);assert.equal(target.stage.units.length,before.units.filter(u=>u.team===0).length);}checks.push('custom saved formation recall across all TEAMs');
e=new FieldEditor();e.applyTeamPreset(1,teamPresets[0]);const base=e.stage.units.filter(u=>u.team===1);custom=saveTeam('B-origin',e.stage,1);let dest=new FieldEditor();dest.applyTeamPreset(0,custom);const from=base.map(u=>u.type).sort(),to=dest.stage.units.map(u=>u.type).sort();assert.deepEqual(from,to);checks.push('B-origin custom formation mirrors to A');
const stage=records=>({units:records.map((u,id)=>({id,team:u[0],type:u[1],x:u[2],z:u[3],yaw:0})),terrain:[]});
let b=new Battle([],stage([[0,0,0,0],[1,0,1,0],[1,0,2,0],[2,0,3,0],[3,0,4,0]])),source=b.units[0];b.units[1].receiveDamage(70,source,'punch',b);b.units[1].receiveDamage(999,source,'punch',b);b.units[1].receiveDamage(999,source,'punch',b);ok(b.stats.records.get(0).damage===100&&b.stats.records.get(0).kills===1,'damage is actual HP loss, overkill/duplicate kill excluded');for(let i=0;i<90;i++)b.step(1/30);ok(!b.units.find(u=>u.id===1)&&b.stats.records.has(1),'stats retained after corpse pruned');
b=new Battle([],stage([[0,16,0,0],[1,0,1,0],[2,0,2,0],[3,0,3,0]]));b.performAttack(b.units[0],b.units[1]);ok(b.report.mvp.kills===3&&b.report.damageLeader.damage===300,'all-team attack credits exact kills and damage');ok(b.report.teams[0].kills===3&&b.report.teams.slice(1).every(t=>t.survivors===0),'team report survivors/kills');const report=JSON.stringify(b.report);b.step(3);ok(JSON.stringify(b.report)===report,'final report frozen after ending animation');
b=new Battle([],stage([[0,0,0,0],[0,0,-5,0],[1,0,1,0],[1,0,10,0]]));const deadSource=b.units[0],target=b.units[2];b.launch(deadSource,target,100,'spear');deadSource.receiveDamage(100,target,'punch',b);deadSource.deadTime=3;b.time=3;b.nextPrune=0;b.step(.01);ok(!b.units.includes(deadSource),'source pruned before projectile resolves');b.step(1);ok(b.stats.records.get(deadSource.id).kills===1,'posthumous projectile kill remains credited');
b=new Battle([],stage([[0,0,0,0],[1,0,2,0]]));let extra=b.addCharacter(3,0,4,0);b.units[0].receiveDamage(100,extra,'punch',b);b.units[1].receiveDamage(100,extra,'punch',b);ok(b.report.teams[3].reinforcements===1&&b.report.teams[3].survivors===1&&b.report.mvp.id===extra.id,'reinforcement and MVP report');
b=new Battle([],stage([[0,17,0,0],[1,17,2,0]]));b.checkResult();ok(b.result==='DRAW'&&b.report.mvp===null&&b.report.damageLeader===null,'immune draw with no false MVP');
const cam=new SpectatorCamera(),rig=new CameraRig(cam),u={hp:100,x:1,y:2,z:3,data:{size:1}};const pose=JSON.stringify({target:cam.target,yaw:cam.yaw,pitch:cam.pitch,distance:cam.distance});assert(rig.follow(u));assert.deepEqual(cam.target,[1,3,3]);u.x=9;rig.update(.1);ok(cam.target[0]>1&&cam.target[0]<9,'follow smoothing uses live transform');rig.release();assert.equal(JSON.stringify({target:cam.target,yaw:cam.yaw,pitch:cam.pitch,distance:cam.distance}),pose);checks.push('free camera pose restored after follow');rig.follow(u);u.hp=0;rig.update(.1);ok(rig.mode==='free'&&rig.subject===null,'follow target death auto-releases');assert(!rig.follow(u));
const rules=new BattleRules({costLimit:20,allowedCharacters:[0],placementAreas:[{team:0,minX:-49,maxX:0,minZ:-34,maxZ:34}]});e=new FieldEditor(undefined,new GameMode('test',rules));e.placeGroup(0,[0,0],-10,0);assert.throws(()=>e.placeGroup(0,[0],-15,0));assert.throws(()=>e.placeGroup(0,[3],-15,0));assert.throws(()=>e.placeGroup(1,[0],15,0));checks.push('rule boundary: batch cost, allowed characters, team areas');e=new FieldEditor();e.placeGroup(0,[17,19],-20,0);ok(e.stage.units.length===2,'Sandbox does not enforce cost');
let restrictedStage=stage([[0,0,-10,0],[1,0,-15,0]]);b=new Battle([],restrictedStage,new GameMode('test',new BattleRules({costLimit:10})));ok(b.addCharacter(0,0,-20,0)===null,'reinforcements obey injected cost rule');let callback=0;b=new Battle([],restrictedStage,new GameMode('test',new BattleRules({timeLimit:1,victoryCondition:b=>{callback++;return b.time>=b.rules.timeLimit?'TEST RESULT':null}})));b.step(1);ok(callback>0&&b.result==='TEST RESULT','victory policy/time metadata delegated to rule');
function seed(){let state=42;Math.random=()=>((state=(Math.imul(state,1664525)+1013904223)>>>0)/4294967296);}
let benchmarks=[];for(const n of [50,100,300]){let old,newB;for(const [version,C] of [['v8',OldBattle],['v9',Battle]]){seed();let battle=new C([[n],[n]]),ms=[];for(let i=0;i<1800&&!battle.result;i++){let start=performance.now();battle.step(1/30);ms.push(performance.now()-start);}ms.sort((a,b)=>a-b);benchmarks.push({version,scenario:`${n}vs${n}`,meanMs:ms.reduce((a,b)=>a+b,0)/ms.length,p95Ms:ms[Math.floor(ms.length*.95)],simTime:battle.time,result:battle.result,attacks:battle.events});if(version==='v8')old=battle;else newB=battle;}assert.equal(old.result,newB.result);assert.equal(old.time,newB.time);assert.equal(old.events,newB.events);assert.deepEqual(old.alive,newB.alive);const casualties=newB.stats.teams.reduce((s,t,i)=>s+t.spawned-newB.alive[i],0),kills=newB.stats.teams.reduce((s,t)=>s+t.kills,0);assert.equal(casualties,kills);}checks.push('50/100/300 vs same: fixed-seed Phase2/3 identical winner, time, attacks, survivors; kills reconcile');
e=new FieldEditor();for(let t=0;t<4;t++)e.applyTeamPreset(t,teamPresets[t===3?5:0]);b=new Battle([],e.snapshot());for(let i=0;i<1800&&!b.result;i++)b.step(1/30);ok(b.events>0&&b.units.every(u=>Number.isFinite(u.hp)),'four-way preset battle with gigant');
const results={checks,benchmarks};fs.writeFileSync(new URL('./logic-rerun-results.json',import.meta.url),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
