import assert from 'node:assert/strict';import fs from 'node:fs';import {Battle} from '../simulation.js';import {Battle as OldBattle} from './baseline-v9/simulation.js';import {GameMode,BattleRules} from '../rules.js';import {characterData} from '../data.js';import {characterData as oldData} from './baseline-v9/data.js';import {FieldEditor} from '../editor.js';import {teamPresets} from '../team-presets.js';
const stage=arr=>({terrain:[],units:arr.map(([team,type,x,z],id)=>({id,team,type,x,z,yaw:0}))});let checks=[];function ok(v,label){assert(v,label);checks.push(label);}
assert.deepEqual(characterData,oldData);checks.push('all combat values + metadata unchanged');
let b=new Battle([],stage([[0,0,-1,0],[1,0,1,0],[2,17,0,1],[3,0,20,0]]));let god=b.interventions;god.cast('shock',0,0);ok(b.units[0].hp===88&&b.units[1].hp===88&&b.units[3].hp===100,'shock hits both teams only within radius');ok(b.units[0].vx<0&&b.units[1].vx>0&&b.units[0].vy>0,'shock radial launch and vertical impulse');ok(b.units[2].hp===100&&b.units[2].vy>0,'immune god HP preserved but shock can move it');assert.throws(()=>god.cast('shock',0,0));ok(god.uses.shock===1&&b.units[0].hp===88,'cooldown blocks repeat without damage/count');god.tick(2);god.cast('shock',0,0);ok(god.uses.shock===2,'independent real-second cooldown resets');
god.cast('heal',0,0,{team:0});ok(b.units[0].hp===100&&b.units[1].hp===76,'TEAM-only healing');god.tick(3);god.cast('heal',0,0);ok(b.units[1].hp===100&&b.units.every(u=>u.hp<=u.maxHp),'all-team healing capped at max HP');for(let t=0;t<4;t++)assert.equal(b.hp[t],b.units.filter(u=>u.team===t).reduce((s,u)=>s+u.hp,0));checks.push('healing aggregate HP agrees with unit HP');
b.units[3].x=2;b.units[3].z=2;god.cast('lightning',0,0);ok(b.units[0].hp===10&&b.units[1].hp===10&&b.units[3].hp===10&&b.units[2].hp===100,'lightning uses current positions, all teams, immune HP');ok(b.effects.some(e=>e.kind==='divineLightning'),'lightning effect emitted');
b=new Battle([],stage([[0,0,-1,0],[1,0,1,0]]));for(const u of b.units)u.hp=10;b.hp=[10,10,0,0];b.interventions.cast('shock',0,0);ok(b.result==='DRAW'&&b.alive.every(n=>n===0),'area damage applied atomically before win decision');ok(b.report.interventions.uses.shock===1&&b.report.interventions.kills===2&&b.report.mvp===null&&b.report.teams.every(t=>t.kills===0),'god kills counted separately from character MVP');assert.throws(()=>b.interventions.cast('heal',0,0));const frozen=JSON.stringify(b.report);b.step(3);assert.equal(JSON.stringify(b.report),frozen);checks.push('post-result cast blocked and report frozen');
b=new Battle([],stage([[0,0,-20,0],[1,0,20,0]]));let plan=b.interventions.cast('reinforcement',0,0,{team:3,types:[19,...Array(10).fill(3)],formation:'square',density:'normal'});ok(plan.count===11&&b.alive[3]===11&&b.stats.teams[3].reinforcements===11,'mixed gigant reinforcement group uses existing addCharacter');for(let t=0;t<4;t++)assert.equal(b.initial[t],b.teams[t].reduce((s,u)=>s+u.maxHp,0));ok(b.interventions.reinforced===11,'reinforcement intervention units tracked');for(let i=0;i<b.units.length;i++)for(let j=0;j<i;j++)assert(Math.hypot(b.units[i].x-b.units[j].x,b.units[i].z-b.units[j].z)>=b.units[i].data.radius+b.units[j].data.radius+.08-1e-6);checks.push('reinforcements do not overlap others');
let rules=new BattleRules({godAbilities:false});b=new Battle([],stage([[0,0,-20,0],[1,0,20,0]]),new GameMode('test',rules));for(const key of ['shock','heal','lightning','reinforcement'])assert.throws(()=>b.interventions.cast(key,0,0));ok(b.interventions.uses.shock===0,'all god abilities prohibited via rules');
rules=new BattleRules({godAbilities:{lightning:{maxUses:3,cooldown:1},heal:{enabled:false},shock:{maxUses:0}}});b=new Battle([],stage([[0,0,-20,0],[1,0,20,0]]),new GameMode('test',rules));for(let i=0;i<3;i++){b.interventions.cast('lightning',0,0);b.interventions.tick(1);}assert.throws(()=>b.interventions.cast('lightning',0,0));assert.throws(()=>b.interventions.cast('heal',0,0));assert.throws(()=>b.interventions.cast('shock',0,0));ok(b.interventions.uses.lightning===3,'per-ability limits/cooldown/disable through BattleRules');
rules=new BattleRules({costLimit:20,allowedCharacters:[0],placementAreas:[{minX:-49,maxX:49,minZ:-34,maxZ:34}]});b=new Battle([],stage([[0,0,-20,0],[1,0,20,0]]),new GameMode('test',rules));let initial=JSON.stringify([b.alive,b.stats.teams,b.interventions.summary()]);assert.throws(()=>b.interventions.cast('reinforcement',0,0,{team:0,types:[0,0]}));assert.throws(()=>b.interventions.cast('reinforcement',0,0,{team:0,types:[19]}));assert.equal(JSON.stringify([b.alive,b.stats.teams,b.interventions.summary()]),initial);checks.push('failed reinforcement rule validation changes neither units nor cooldown/counters');
let e=new FieldEditor();for(let x=-40;x<=40;x+=8)for(let z=-25;z<=25;z+=5)e.stage.terrain.push({id:e.nextId++,type:'wall',x,z,yaw:0,scale:3});b=new Battle([],e.stage);initial=JSON.stringify(b.interventions.summary());assert.throws(()=>b.interventions.cast('reinforcement',0,0,{team:0,types:Array(100).fill(19)}));assert.equal(JSON.stringify(b.interventions.summary()),initial);checks.push('no-space group fails atomically');
let benchmarks=[];let randomSeed=1;function reset(){randomSeed=42;Math.random=()=>((randomSeed=(Math.imul(randomSeed,1664525)+1013904223)>>>0)/4294967296);}
for(const n of [50,100,300]){let values=[];for(const [version,C] of [['v9',OldBattle],['v10',Battle]]){reset();b=new C([[n],[n]]);let times=[];for(let i=0;i<1800&&!b.result;i++){const st=performance.now();b.step(1/30);times.push(performance.now()-st);}times.sort((a,b)=>a-b);benchmarks.push({version,scenario:`${n}vs${n}`,meanMs:times.reduce((s,n)=>s+n,0)/times.length,p95Ms:times[Math.floor(times.length*.95)],result:b.result,time:b.time,events:b.events});values.push([b.result,b.time,b.events,b.alive]);}assert.deepEqual(...values);}checks.push('50/100/300 vs same: two-team seeded combat identical to Phase3');
reset();b=new Battle([[300],[300]]);let casts=[];for(let i=0;i<25;i++){b.interventions.tick(4);const st=performance.now();b.interventions.cast('shock',0,0);casts.push(performance.now()-st);}casts.sort((a,b)=>a-b);benchmarks.push({scenario:'shock 600 units',meanMs:casts.reduce((s,n)=>s+n,0)/casts.length,p95Ms:casts[Math.floor(casts.length*.95)]});ok(casts.every(Number.isFinite),'600-unit shock bounded CPU cost');
e=new FieldEditor();for(let t=0;t<4;t++)e.applyTeamPreset(t,teamPresets[0]);b=new Battle([],e.stage);let times=[];for(let i=0;i<900&&!b.result;i++){let st=performance.now();b.step(1/30);times.push(performance.now()-st);}times.sort((a,b)=>a-b);benchmarks.push({scenario:'four-team mixed 208',meanMs:times.reduce((s,n)=>s+n,0)/times.length,p95Ms:times[Math.floor(times.length*.95)]});ok(b.events>0&&b.fronts.pressure.every(a=>a.every(n=>n>=0)),'mixed four-team combat and target claims remain valid');
fs.writeFileSync(new URL('./rerun-phase4-god-results.json',import.meta.url),JSON.stringify({checks,benchmarks},null,2));console.log(JSON.stringify({checks,benchmarks},null,2));
