/** Actual game-v12.js pointer handlers with a small DOM/WebGL adapter, not a browser test. */
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),checks=[];const ok=(v,s)=>{assert(v,s);checks.push(s)};
export async function environment(width=1000,height=650){const ids=new Map(),all=[],listeners=new Map();let serial=0;
 class Element{constructor(tag='div',attributes={}){this.tagName=tag.toUpperCase();this.attributes={};this.children=[];this.style={};this.dataset={};this.hidden=false;this.disabled=false;this._value='';this._text='';this.classList={add(){},remove(){},toggle(){}};this.listeners=new Map();all.push(this);for(const [k,v] of Object.entries(attributes))this.setAttribute(k,v);}
 set id(v){this.attributes.id=v;ids.set(v,this);}get id(){return this.attributes.id||'';}set value(v){this._value=String(v)}get value(){if(this.tagName==='SELECT'&&!this._value)return this.children.find(c=>c.attributes.selected!==undefined)?.value||this.children[0]?.value||'';return this._value;}
 get options(){return this.children}get selectedOptions(){return this.children.filter(c=>c.value===this.value).slice(0,1)}set textContent(t){this._text=String(t)}get textContent(){return this._text||this.children.map(c=>c.textContent).join('')}
 set innerHTML(html){this.children=[];parse(html,this);}get innerHTML(){return '';}
 setAttribute(k,v){this.attributes[k]=String(v);if(k==='id'){ids.set(String(v),this);}if(k==='value')this._value=String(v);if(k==='hidden')this.hidden=true;if(k==='disabled')this.disabled=true;if(k.startsWith('data-'))this.dataset[k.slice(5)]=String(v)}getAttribute(k){return this.attributes[k]??null;}
 append(...els){for(const el of els){if(el.parentElement)el.parentElement.children=el.parentElement.children.filter(e=>e!==el);this.children.push(el);el.parentElement=this;}}prepend(...els){this.append(...els)}after(){}replaceChildren(...els){this.children=[];this.append(...els)}closest(){return this.parentElement||new Element('label')}
 querySelector(q){return q==='small'?this.children.find(c=>c.tagName==='SMALL'):new Element(q)}addEventListener(name,fn){if(!this.listeners.has(name))this.listeners.set(name,[]);this.listeners.get(name).push(fn)}getBoundingClientRect(){return {left:0,top:0,right:width,bottom:height,width,height}}setPointerCapture(){}
 getContext(){return new Proxy({}, {get:(_,k)=>k==='getShaderParameter'||k==='getProgramParameter'?()=>true:k==='getUniformLocation'||String(k).startsWith('create')?()=>({id:serial++}):String(k).toUpperCase()===k?serial++:()=>{}})}
 }
 function attrs(s){const a={};for(const m of s.matchAll(/([\w-]+)(?:="([^"]*)")?/g))a[m[1]]=m[2]??'';return a;}
 function parse(html,parent){const re=/<(input|select|option|button|span|small|b|div|canvas|progress|section|strong|p|label|details|output|h2|h3|tbody)\b([^>]*)>([^<]*)/g;for(const m of html.matchAll(re)){const a=attrs(m[2]);if(!a.id&&m[1]!=='option'&&!a['data-tool']&&!a['data-team'])continue;const el=new Element(m[1],a);el.textContent=m[3];parent?.append(el);if(m[1]==='select'){const end=html.indexOf('</select>',m.index);el.innerHTML=html.slice(m.index+m[0].length,end);}}
 }
 parse(fs.readFileSync(path.join(root,'index.html'),'utf8'));const named=new Map();for(const q of ['.hud','.controls','.placement'])named.set(q,new Element('div'));
 const document={body:new Element('body'),getElementById:id=>ids.get(id),createElement:t=>new Element(t),querySelector:q=>named.get(q)||ids.get(q.replace(/^#/,'')),querySelectorAll:q=>q==='.row input'?all.filter(el=>/^n\d_\d+$/.test(el.id)):q==='#editModeButtons button'?all.filter(el=>el.dataset.tool):q==='#selectTeams button'?all.filter(el=>el.dataset.team):[]};
 const window={addEventListener:(k,fn)=>{if(!listeners.has(k))listeners.set(k,[]);listeners.get(k).push(fn)}};const storage=new Map();const context=vm.createContext({document,window,navigator:{},location:{protocol:'http:',reload(){}},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},requestAnimationFrame(){},devicePixelRatio:1,performance,console,queueMicrotask,confirm:()=>true,setTimeout,clearTimeout});
 const cache=new Map();const make=file=>{if(cache.has(file))return cache.get(file);let source=fs.readFileSync(file,'utf8');if(file.endsWith('/game-v12.js'))source+=`\nexport const testing={get editor(){return editor},get battle(){return battle},get selection(){return unitSelection},get camera(){return camera},get marker(){return marker},get renderer(){return renderer},get pointers(){return pointers},get gesture(){return selectionGesture},chooseMode,get mode(){return currentMode},openEditor,beginBattle,refreshEditor,selectMode,frame,groupScreen};`;const mod=new vm.SourceTextModule(source,{context,identifier:file});cache.set(file,mod);return mod;};const game=make(path.join(root,'game-v12.js'));await game.link((specifier,referencer)=>make(path.resolve(path.dirname(referencer.identifier),specifier)));await game.evaluate();const api=game.namespace.testing;assert(api.editor,ids.get('notice')?.textContent);const canvas=ids.get('canvas');
 const event=(pointerId,x,y,extra={})=>({pointerId,pointerType:width<600?'touch':'mouse',clientX:x,clientY:y,button:0,preventDefault(){},target:canvas,...extra});const send=(kind,id,p,extra={})=>canvas['onpointer'+kind](event(id,p[0],p[1],extra));const drag=(a,b,extra={})=>{send('down',1,a,extra);for(let i=1;i<=5;i++)send('move',1,[a[0]+(b[0]-a[0])*i/5,a[1]+(b[1]-a[1])*i/5],extra);send('up',1,b,extra)};const tap=(p,extra={})=>{send('down',1,p,extra);send('up',1,p,extra)};
 const project=(u,y=1.3)=>{api.camera.update(width/height);return api.camera.project(u.x,api.battle.terrain.heightAt(u.x,u.z)+y,u.z,width,height)};
 return {api,ids,all,canvas,listeners,send,drag,tap,project,width,height};}
for(const [label,w,h] of [['PC',1000,650],['Android相当イベント',370,506]]){
 const env=await environment(w,h),{api,ids,send,drag,tap,project}=env;
 function stage(n=10){api.editor.clearUnits();api.editor.stage.terrain=[];api.editor.placeGroup(0,Array(n).fill(0),-18,-8);api.editor.placeGroup(1,[0,0],30,20);api.openEditor(api.editor.snapshot());api.selectMode('select');}
 stage(1);const first=api.editor.stage.units[0];tap(project(first),{pointerType:label==='PC'?'mouse':'touch'});ok(api.selection.ids.size===1,`${label} 1体タップ選択`);let before=JSON.stringify(api.editor.snapshot()),hist=api.editor.history.length;const q=api.groupScreen(),destination=api.camera.project(-8,0,-8,w,h);drag([q.x,q.y],destination,{pointerType:label==='PC'?'mouse':'touch'});ok(JSON.stringify(api.editor.snapshot())!==before&&api.editor.history.length===hist+1,`${label} 選択直後のドラッグ移動・一回確定`);ids.get('selectionUndo').onclick();ok(JSON.stringify(api.editor.snapshot())===before,`${label} UI Undo`);
 for(const n of [10,50]){stage(n);const projected=api.editor.stage.units.filter(u=>u.team===0).map(u=>project(u));const a=[Math.min(...projected.map(p=>p[0]))-30,Math.min(...projected.map(p=>p[1]))-30],b=[Math.max(...projected.map(p=>p[0]))+30,Math.max(...projected.map(p=>p[1]))+30];const cameraBefore=JSON.stringify({yaw:api.camera.yaw,pitch:api.camera.pitch,target:api.camera.target,distance:api.camera.distance});drag(a,b);ok(api.selection.ids.size===n,`${label} ${n}体ドラッグ範囲選択`);assert.equal(JSON.stringify({yaw:api.camera.yaw,pitch:api.camera.pitch,target:api.camera.target,distance:api.camera.distance}),cameraBefore);const units=api.editor.stage.units.filter(u=>api.selection.ids.has(u.id)),old=units.map(u=>({...u})),c=api.groupScreen();drag([c.x,c.y],api.camera.project(-8,0,2,w,h));const moved=api.editor.stage.units.filter(u=>api.selection.ids.has(u.id));assert(moved[0].x!==old[0].x);for(let i=0;i<n;i++){assert(Math.abs((moved[i].x-moved[0].x)-(old[i].x-old[0].x))<1e-9);assert(Math.abs((moved[i].z-moved[0].z)-(old[i].z-old[0].z))<1e-9);}ok(true,`${label} ${n}体移動・陣形維持・選択操作中カメラ不変`);}
 const teams=env.all.filter(el=>el.dataset.team);teams.find(el=>el.dataset.team==='0').onclick();ok(api.selection.ids.size===50,`${label} TEAM全選択ボタン`);before=JSON.stringify(api.editor.snapshot());hist=api.editor.history.length;const c=api.groupScreen();send('down',1,[c.x,c.y]);send('move',1,[c.x+25,c.y]);assert(api.marker?.selectionPreview);assert.equal(JSON.stringify(api.editor.snapshot()),before);const distance=api.camera.distance;send('down',2,[c.x+70,c.y]);send('move',2,[c.x+110,c.y+10]);send('move',1,[c.x+35,c.y+10]);send('up',2,[c.x+110,c.y+10]);send('move',1,[c.x+45,c.y+10]);send('up',1,[c.x+45,c.y+10]);ok(JSON.stringify(api.editor.snapshot())===before&&api.editor.history.length===hist&&api.selection.ids.size===50&&api.camera.distance!==distance,`${label} 移動途中の2本指パン・ピンチで移動取消／選択保持`);
 let selected=api.editor.stage.units[0],p=project(selected);send('down',1,p);send('move',1,[p[0]+20,p[1]]);send('cancel',1,[p[0]+20,p[1]]);ok(JSON.stringify(api.editor.snapshot())===before&&api.pointers.size===0,`${label} pointercancelで無変更`);
 p=project(api.editor.stage.units[0]);send('down',1,p);send('move',1,[p[0]+20,p[1]]);api.selectMode('camera');send('up',1,[p[0]+20,p[1]]);ok(JSON.stringify(api.editor.snapshot())===before,`${label} モード変更で移動取消`);
 const yaw=api.camera.yaw;drag([w*.45,h*.45],[w*.55,h*.45]);ok(api.camera.yaw!==yaw&&api.selection.ids.size===50,`${label} カメラ回転・選択保持`);
 api.selectMode('select');ids.get('selectionClear').onclick();ok(api.selection.ids.size===0&&ids.get('selectionCount').textContent==='選択中：0体',`${label} 選択解除・数表示`);tap(project(api.editor.stage.units[0]));tap(project(api.editor.stage.units[1]),{shiftKey:true});ok(api.selection.ids.size===2,`${label} Shift追加選択`);
 api.selectMode('move');tap(api.camera.project(-10,0,-10,w,h));ok(api.selection.ids.size===2,`${label} 明示的移動ボタン・地面タップでも陣形保持`);
 api.selectMode('select');before=JSON.stringify(api.editor.snapshot());hist=api.editor.history.length;const invalidStart=api.groupScreen();drag([invalidStart.x,invalidStart.y],api.camera.project(55,0,0,w,h));ok(JSON.stringify(api.editor.snapshot())===before&&api.editor.history.length===hist,`${label} 無効移動は無変更・Undo消費なし`);
 api.selectMode('select');const boxStart=[w*.1,h*.1];send('down',1,boxStart);send('move',1,[w*.2,h*.2]);assert(!ids.get('selectionRect').hidden);send('down',2,[w*.6,h*.5]);send('move',2,[w*.7,h*.5]);send('up',2,[w*.7,h*.5]);send('up',1,[w*.2,h*.2]);ok(ids.get('selectionRect').hidden&&JSON.stringify(api.editor.snapshot())===before,`${label} 範囲選択途中の2本指で選択取消`);
 for(const fn of env.listeners.get('keydown')||[])fn({key:'Escape',target:{tagName:'BODY'}});ok(api.selection.ids.size===0,`${label} Escape選択解除`);
 ids.get('presetName').value='Phase45-save';ids.get('savePreset').onclick();api.editor.clearUnits();api.refreshEditor();ids.get('presetList').value='Phase45-save';ids.get('loadPreset').onclick();ok(JSON.stringify(api.editor.snapshot())===before&&api.selection.ids.size===0,`${label} 移動後の保存・読込と選択状態リセット`);
 api.beginBattle();ok(ids.get('selectionToolbar').hidden&&api.selection.ids.size===0,`${label} 戦闘開始で編集ジェスチャー分離`);api.frame(performance.now());
}
const env=await environment();env.api.editor.clearUnits();env.api.editor.placeGroup(0,Array(300).fill(0),0,0);env.api.openEditor(env.api.editor.snapshot());env.api.selectMode('select');env.api.frame(performance.now());const calls=env.api.renderer.drawCalls,parts=env.api.renderer.parts;env.api.selection.team(env.api.editor.stage.units,0);env.api.frame(performance.now());ok(env.api.renderer.drawCalls===calls&&env.api.renderer.parts-parts===1500,'300体選択ハイライト：既存インスタンス描画に1500パーツ追加・Draw Call増加0（WebGLアダプター）');
fs.writeFileSync(new URL('phase45-input-results.json',import.meta.url),JSON.stringify({method:'Node VM + actual game-v12.js + mock DOM/WebGL; not real Android/browser',checks},null,2));console.log(JSON.stringify({checks},null,2));
