const TAU=Math.PI*2;
export function multiply(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
const norm=a=>{let d=Math.hypot(...a)||1;return a.map(v=>v/d)},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((n,v,i)=>n+v*b[i],0);
export class SpectatorCamera{
 constructor(){this.target=[0,0,0];this.yaw=.65;this.pitch=.8;this.distance=100;this.matrix=new Float32Array(16);this.eye=[0,0,0];}
 reset(){this.target=[0,0,0];this.yaw=.65;this.pitch=.8;this.distance=100;}
 orbit(dx,dy){this.yaw-=dx*.006;this.pitch=Math.max(.16,Math.min(1.45,this.pitch+dy*.005));}
 zoom(factor){this.distance=Math.max(5,Math.min(190,this.distance*factor));}
 pan(dx,dy){let s=this.distance*.0015;this.target[0]+=(-Math.cos(this.yaw)*dx-Math.sin(this.yaw)*dy)*s;this.target[2]+=(Math.sin(this.yaw)*dx-Math.cos(this.yaw)*dy)*s;this.target[0]=Math.max(-50,Math.min(50,this.target[0]));this.target[2]=Math.max(-35,Math.min(35,this.target[2]));}
 update(aspect){let t=this.target,d=this.distance,p=this.pitch,y=this.yaw;this.eye=[t[0]+Math.sin(y)*Math.cos(p)*d,t[1]+Math.sin(p)*d,t[2]+Math.cos(y)*Math.cos(p)*d];let z=norm(this.eye.map((v,i)=>v-t[i])),x=norm(cross([0,1,0],z)),up=cross(z,x);let view=new Float32Array([x[0],up[0],z[0],0,x[1],up[1],z[1],0,x[2],up[2],z[2],0,-dot(x,this.eye),-dot(up,this.eye),-dot(z,this.eye),1]);let f=1/Math.tan(.55),near=.1,far=500;let proj=new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);this.matrix=multiply(proj,view);}
 groundPoint(px,py,w,h){const forward=norm(this.target.map((v,i)=>v-this.eye[i])),right=norm(cross(forward,[0,1,0])),up=cross(right,forward),nx=(px/w*2-1)*Math.tan(.55)*w/h,ny=(1-py/h*2)*Math.tan(.55),ray=norm(forward.map((v,i)=>v+right[i]*nx+up[i]*ny));if(ray[1]>=-.0001)return null;const t=-this.eye[1]/ray[1];if(t<=0)return null;return {x:this.eye[0]+ray[0]*t,z:this.eye[2]+ray[2]*t};}
 project(x,y,z,w,h){let m=this.matrix,q=m[3]*x+m[7]*y+m[11]*z+m[15];if(q<=0)return null;return [(m[0]*x+m[4]*y+m[8]*z+m[12])/q*w/2+w/2,-(m[1]*x+m[5]*y+m[9]*z+m[13])/q*h/2+h/2];}
}
function geometry(octa=false){let positions=[],normals=[];const v=octa?[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]]:[[-.5,-.5,-.5],[.5,-.5,-.5],[.5,.5,-.5],[-.5,.5,-.5],[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]];const faces=octa?[[2,0,4],[2,4,1],[2,1,5],[2,5,0],[3,4,0],[3,1,4],[3,5,1],[3,0,5]]:[[0,3,2],[0,2,1],[4,5,6],[4,6,7],[0,4,7],[0,7,3],[1,2,6],[1,6,5],[3,7,6],[3,6,2],[0,1,5],[0,5,4]];for(let f of faces){let a=v[f[0]],b=v[f[1]],c=v[f[2]],n=norm(cross(b.map((x,i)=>x-a[i]),c.map((x,i)=>x-a[i])));for(let i of f){positions.push(...v[i]);normals.push(...n)}}return {positions:new Float32Array(positions),normals:new Float32Array(normals),count:positions.length/3};}
export class Renderer3D{
 constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{antialias:false,alpha:false});if(!this.gl)throw Error('この端末ではWebGL2を利用できません。Chromeで開き直してください。');let gl=this.gl;
 let vs=`#version 300 es\nprecision highp float;layout(location=0) in vec3 pos;layout(location=1) in vec3 normal;layout(location=2) in mat4 model;layout(location=6) in vec3 color;uniform mat4 vp;out vec3 col;out vec3 wp;void main(){vec4 p=model*vec4(pos,1.);wp=p.xyz;vec3 n=normalize(mat3(model)*normal);float light=.5+.5*max(0.,dot(n,normalize(vec3(-.4,1.,.6))));col=color*light;gl_Position=vp*p;}`;
 let fs=`#version 300 es\nprecision highp float;in vec3 col;in vec3 wp;out vec4 outColor;uniform vec3 eye;void main(){float fog=smoothstep(85.,210.,distance(eye,wp));outColor=vec4(mix(col,vec3(.10,.16,.22),fog),1.);}`;
 const shader=(type,source)=>{let s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};this.program=gl.createProgram();gl.attachShader(this.program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(this.program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(this.program);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.program));this.vp=gl.getUniformLocation(this.program,'vp');this.eye=gl.getUniformLocation(this.program,'eye');this.batches=[this.makeBatch(geometry()),this.makeBatch(geometry(true))];this.colors=[[.18,.72,1],[1,.25,.37]];this.parts=0;this.models=new Map([['stick',(u,b,c,s)=>this.humanoid(u,b,c,s)],['muscle',(u,b,c,s)=>this.humanoid(u,b,c,s)]]);this.contextLost=false;canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.contextLost=true});canvas.addEventListener('webglcontextrestored',()=>location.reload());}
 makeBatch(g){let gl=this.gl,vao=gl.createVertexArray();gl.bindVertexArray(vao);for(let [loc,data] of [[0,g.positions],[1,g.normals]]){let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);}let buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);for(let i=0;i<4;i++){gl.enableVertexAttribArray(2+i);gl.vertexAttribPointer(2+i,4,gl.FLOAT,false,76,i*16);gl.vertexAttribDivisor(2+i,1);}gl.enableVertexAttribArray(6);gl.vertexAttribPointer(6,3,gl.FLOAT,false,76,64);gl.vertexAttribDivisor(6,1);return {vao,buffer,vertices:g.count,array:new Float32Array(19*2048),n:0};}
 add(matrix,color,head=false){let b=this.batches[head?1:0],offset=b.n*19;if(offset+19>b.array.length){let a=new Float32Array(b.array.length*2);a.set(b.array);b.array=a;}b.array.set(matrix,offset);b.array.set(color,offset+16);b.n++;}
 box(x,y,z,sx,sy,sz,color,yaw=0,head=false){let c=Math.cos(yaw),s=Math.sin(yaw);this.add([c*sx,0,-s*sx,0,0,sy,0,0,s*sz,0,c*sz,0,x,y,z,1],color,head);}
 segment(a,b,r,color){let v=b.map((x,i)=>x-a[i]),length=Math.hypot(...v)||.001,y=norm(v),x=norm(cross(Math.abs(y[1])>.95?[1,0,0]:[0,1,0],y)),z=cross(x,y);this.add([x[0]*r,x[1]*r,x[2]*r,0,y[0]*length,y[1]*length,y[2]*length,0,z[0]*r,z[1]*r,z[2]*r,0,(a[0]+b[0])/2,(a[1]+b[1])/2,(a[2]+b[2])/2,1],color);}
 registerModel(name,builder){this.models.set(name,builder);}
 unit(u,battle,camera,selected){let builder=this.models.get(u.data.modelType)||this.models.get('stick');builder(u,battle,camera,selected);}
 humanoid(u,battle,camera,selected){let c=u.data,scale=c.size,color=u.flash>0?[1,1,1]:this.colors[u.team];let isDead=u.hp<=0;if(isDead&&u.deadTime>1.8)return;let far=Math.hypot(u.x-camera.eye[0],u.z-camera.eye[2])>65,lod=battle.count>1800||far;let walk=u.command.x||u.command.z?Math.sin(u.motion*9+u.id)*.32:0;let attack=u.attack?Math.sin(Math.min(1,u.attack.time/c.windup)*Math.PI)*1.1:0;let fall=isDead?Math.min(1,u.deadTime*3):u.stun>.4?.9:0;let cy=Math.cos(u.yaw),sy=Math.sin(u.yaw);
 const at=(x,y,z)=>{if(fall){let yy=y;y=y*(1-fall)+.2;z+=yy*fall;if(c.weapon==='water')x+=Math.sin(u.motion*12)*fall*.2;}return [u.x+(x*cy+z*sy)*scale,u.y+y*scale,u.z+(-x*sy+z*cy)*scale]};
 let thickness=c.modelType==='muscle'?.38:.10,torso=c.modelType==='muscle'?.72:.13;
 this.segment(at(0,.8,0),at(.03,1.5,0),torso,color);let heads=c.heads||1;for(let i=0;i<heads;i++){let p=at((i-(heads-1)/2)*.32,1.8,0);this.box(...p,.23*scale,.26*scale,.23*scale,color,u.yaw,true);}
 this.segment(at(-.06,.85,0),at(-.25,.12,walk),thickness,color);this.segment(at(.06,.85,0),at(.25,.12,-walk),thickness,color);
 const handL=at(-.40,1.12+attack*.4,.22+attack*.8),handR=at(.40,1.10+attack*.4,.20+attack*.8);this.segment(at(-.10,1.45,0),handL,thickness,color);this.segment(at(.10,1.45,0),handR,thickness,color);
 if(c.modelType==='muscle'){for(let h of [handL,handR])this.box(...h,.4,.4,.4,color,u.yaw,true);}
 if(!lod||c.weapon!=='punch'){let n=Math.min(c.damage.length,5);if(c.weapon==='god'||c.weapon==='muscle')n=1;for(let i=0;i<n;i++){let h=i%2?handL:handR,w=c.weapon==='mixed'?(i?'sword':'hammer'):c.weapon;let metal=[.77,.85,.92],end=[h[0]+sy*.45,h[1]+.55+attack*.3,h[2]+cy*.45];if(w==='hammer'){this.segment(h,end,.07,metal);this.box(...end,.45,.22,.22,metal,u.yaw);}else if(['sword','katana','god','spear','allSpear'].includes(w)){let length=w.includes('Spear')||w==='spear'?1.4:.8;let tip=[h[0]+sy*length,h[1]+.18+attack*.4,h[2]+cy*length];this.segment(h,tip,.06,metal);this.box(...tip,.09,.09,.18,metal,u.yaw,true);}else if(['water','fire'].includes(w))this.box(...h,.20,.20,.20,w==='water'?[.1,.9,1]:[1,.42,.06],0,true);}}
 if(c.immune){let p=at(0,2.18,0);this.box(...p,.33,.16,.33,[1,.85,.2],u.yaw);}if(u===selected)this.box(u.x,.035,u.z,1.8,.05,1.8,[1,.85,.2]);
 }
 draw(battle,camera,selected,marker=null){if(this.contextLost)return;let gl=this.gl,r=this.canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,battle&&battle.count>1000?1:1.5);let w=Math.round(r.width*ratio),h=Math.round(r.height*ratio);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}camera.update(r.width/r.height);this.batches.forEach(b=>b.n=0);
 this.box(0,-.16,0,102,.3,72,[.19,.29,.29]);for(let x=-50;x<=50;x+=5)this.box(x,.004,0,.025,.01,70,[.28,.39,.38]);for(let z=-35;z<=35;z+=5)this.box(0,.004,z,100,.01,.025,[.28,.39,.38]);for(let z of [-22,0,22]){this.box(-48,.1,z,1,.2,5,this.colors[0]);this.box(48,.1,z,1,.2,5,this.colors[1]);}
 if(marker){let color=this.colors[marker.team];for(let i=0;i<16;i++){let a=i/16*TAU;this.box(marker.x+Math.cos(a)*.75,.06,marker.z+Math.sin(a)*.75,.12,.08,.12,color);}this.box(marker.x,.06,marker.z,.2,.08,.2,color);}
 if(battle){for(let u of battle.units){let p=camera.project(u.x,1,u.z,r.width,r.height);if(!p||p[0]<-120||p[0]>r.width+120||p[1]<-120||p[1]>r.height+120)continue;this.unit(u,battle,camera,selected);}
 for(let p of battle.projectiles.slice(0,180)){if(p.time<0)continue;let f=Math.min(1,p.time/p.duration),x=p.sx+(p.tx-p.sx)*f,z=p.sz+(p.tz-p.sz)*f,y=1.1+Math.sin(f*Math.PI)*2;let color=p.kind==='water'?[.1,.8,1]:p.kind==='fire'?[1,.4,.03]:[.92,.88,.7];if(p.kind==='dumbbell'){y=18*(1-f)+.7;this.box(x,y,z,3,.5,.5,[.6,.65,.72]);this.box(x-1.4,y,z,.7,1.8,1.8,[.75,.8,.87]);this.box(x+1.4,y,z,.7,1.8,1.8,[.75,.8,.87]);}else if(p.kind==='spear'){let dx=p.tx-p.sx,dz=p.tz-p.sz,l=Math.hypot(dx,dz)||1;this.segment([x,y,z],[x+dx/l*1.6,y,z+dz/l*1.6],.07,color);}else this.box(x,y,z,p.area?.9:.3,p.area?.9:.3,p.area?.9:.3,color,0,true);}
 for(let e of battle.effects){let f=e.time/e.duration,col=e.kind==='water'?[.15,.85,1]:e.kind==='fire'?[1,.4,.02]:[1,.85,.3];if(e.kind==='lightning'){for(let i=0;i<5;i++){let x=e.x+(i-2)*3;this.segment([x,20,e.z],[x+.8,9,e.z-.8],.16,col);this.segment([x+.8,9,e.z-.8],[x,.1,e.z],.16,col);}}
 else if(e.kind==='allSpear'){for(let i=0;i<30;i++){let x=e.x+Math.sin(i)*i*.4,z=e.z+Math.cos(i)*i*.4;this.segment([x,2,z],[x+(e.team?-1:1)*f*15,1,z+.4],.04,col);}}
 else{let count=e.kind==='water'?5:12;for(let i=0;i<count;i++){let a=i/count*TAU,r=e.radius*f;this.box(e.x+Math.cos(a)*r,.4+Math.sin(f*Math.PI)*2,e.z+Math.sin(a)*r,.16,.16,.16,col,0,true);}}}}
 gl.viewport(0,0,w,h);gl.clearColor(.10,.16,.22,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.useProgram(this.program);gl.uniformMatrix4fv(this.vp,false,camera.matrix);gl.uniform3fv(this.eye,camera.eye);this.parts=0;for(let b of this.batches){gl.bindVertexArray(b.vao);gl.bindBuffer(gl.ARRAY_BUFFER,b.buffer);gl.bufferData(gl.ARRAY_BUFFER,b.array.subarray(0,b.n*19),gl.DYNAMIC_DRAW);gl.drawArraysInstanced(gl.TRIANGLES,0,b.vertices,b.n);this.parts+=b.n;}}
}
