import {characterData} from './data.js';
const characterRadius=type=>characterData[type].radius;
import {teamData} from './teams.js';
import {terrainData} from './terrain.js';
const TAU=Math.PI*2,POSE_KEYS=['x','y','z','yaw','motion','deadTime','stun'];
// Visual timing only: impact remains at the original simulation windup.
export function attackPose(time,windup){const t=time/Math.max(.01,windup);if(t<.82)return -.45*Math.sin(t/.82*Math.PI/2);if(t<1)return -.45+1.8*((t-.82)/.18)**3;if(time<windup+.16)return 1.35;return 1.35*Math.max(0,1-(time-windup-.16)/.29);}
function shadowGeometry(){let p=[],n=[];for(let i=0;i<12;i++){let a=i/12*TAU,b=(i+1)/12*TAU;p.push(0,0,0,Math.cos(a),0,Math.sin(a),Math.cos(b),0,Math.sin(b));n.push(0,1,0,0,1,0,0,1,0);}return {positions:new Float32Array(p),normals:new Float32Array(n),count:p.length/3};}
export function multiply(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
const norm=a=>{let d=Math.hypot(...a)||1;return a.map(v=>v/d)},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((n,v,i)=>n+v*b[i],0);
export class SpectatorCamera{
 constructor(){this.target=[0,0,0];this.yaw=.65;this.pitch=.8;this.distance=100;this.matrix=new Float32Array(16);this.eye=[0,0,0];}
 reset(){this.target=[0,0,0];this.yaw=.65;this.pitch=.8;this.distance=100;}
 orbit(dx,dy){this.yaw-=dx*.006;this.pitch=Math.max(.16,Math.min(1.45,this.pitch+dy*.005));}
 zoom(factor){this.distance=Math.max(5,Math.min(190,this.distance*factor));}
 pan(dx,dy){let s=this.distance*.0015;this.target[0]+=(-Math.cos(this.yaw)*dx-Math.sin(this.yaw)*dy)*s;this.target[2]+=(Math.sin(this.yaw)*dx-Math.cos(this.yaw)*dy)*s;this.target[0]=Math.max(-50,Math.min(50,this.target[0]));this.target[2]=Math.max(-35,Math.min(35,this.target[2]));}
 update(aspect){let t=this.target,d=this.distance,p=this.pitch,y=this.yaw;this.eye=[t[0]+Math.sin(y)*Math.cos(p)*d,t[1]+Math.sin(p)*d,t[2]+Math.cos(y)*Math.cos(p)*d];let z=norm(this.eye.map((v,i)=>v-t[i])),x=norm(cross([0,1,0],z)),up=cross(z,x);let view=new Float32Array([x[0],up[0],z[0],0,x[1],up[1],z[1],0,x[2],up[2],z[2],0,-dot(x,this.eye),-dot(up,this.eye),-dot(z,this.eye),1]);let f=1/Math.tan(.55),near=.1,far=500;let proj=new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);this.matrix=multiply(proj,view);}
 groundPoint(px,py,w,h,terrain=null){const forward=norm(this.target.map((v,i)=>v-this.eye[i])),right=norm(cross(forward,[0,1,0])),up=cross(right,forward),nx=(px/w*2-1)*Math.tan(.55)*w/h,ny=(1-py/h*2)*Math.tan(.55),ray=norm(forward.map((v,i)=>v+right[i]*nx+up[i]*ny));if(ray[1]>=-.0001)return null;const t=-this.eye[1]/ray[1];if(t<=0)return null;if(terrain?.hills.length){let prev=0;for(let at=2;at<=t+2;at+=2){let x=this.eye[0]+ray[0]*at,z=this.eye[2]+ray[2]*at,y=this.eye[1]+ray[1]*at;if(y<=terrain.heightAt(x,z)){let lo=prev,hi=at;for(let j=0;j<18;j++){let m=(lo+hi)/2,mx=this.eye[0]+ray[0]*m,mz=this.eye[2]+ray[2]*m;if(this.eye[1]+ray[1]*m>terrain.heightAt(mx,mz))lo=m;else hi=m;}return {x:this.eye[0]+ray[0]*hi,z:this.eye[2]+ray[2]*hi};}prev=at;}}return {x:this.eye[0]+ray[0]*t,z:this.eye[2]+ray[2]*t};}
 project(x,y,z,w,h){let m=this.matrix,q=m[3]*x+m[7]*y+m[11]*z+m[15];if(q<=0)return null;return [(m[0]*x+m[4]*y+m[8]*z+m[12])/q*w/2+w/2,-(m[1]*x+m[5]*y+m[9]*z+m[13])/q*h/2+h/2];}
}
function geometry(octa=false){let positions=[],normals=[];const v=octa?[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]]:[[-.5,-.5,-.5],[.5,-.5,-.5],[.5,.5,-.5],[-.5,.5,-.5],[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]];const faces=octa?[[2,0,4],[2,4,1],[2,1,5],[2,5,0],[3,4,0],[3,1,4],[3,5,1],[3,0,5]]:[[0,3,2],[0,2,1],[4,5,6],[4,6,7],[0,4,7],[0,7,3],[1,2,6],[1,6,5],[3,7,6],[3,6,2],[0,1,5],[0,5,4]];for(let f of faces){let a=v[f[0]],b=v[f[1]],c=v[f[2]],n=norm(cross(b.map((x,i)=>x-a[i]),c.map((x,i)=>x-a[i])));for(let i of f){positions.push(...v[i]);normals.push(...n)}}return {positions:new Float32Array(positions),normals:new Float32Array(normals),count:positions.length/3};}
export class Renderer3D{
 constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{antialias:false,alpha:false});if(!this.gl)throw Error('この端末ではWebGL2を利用できません。Chromeで開き直してください。');let gl=this.gl;
 let vs=`#version 300 es\nprecision highp float;layout(location=0) in vec3 pos;layout(location=1) in vec3 normal;layout(location=2) in mat4 model;layout(location=6) in vec3 color;uniform mat4 vp;out vec3 col;out vec3 wp;void main(){vec4 p=model*vec4(pos,1.);wp=p.xyz;vec3 n=normalize(mat3(model)*normal);float light=.68+.32*max(0.,dot(n,normalize(vec3(-.4,1.,.6))));col=color*light;gl_Position=vp*p;}`;
 let fs=`#version 300 es\nprecision highp float;in vec3 col;in vec3 wp;out vec4 outColor;uniform vec3 eye;void main(){float fog=smoothstep(45.,175.,distance(eye,wp));outColor=vec4(mix(col,vec3(.75,.86,.88),fog*.82),1.);}`;
 const shader=(type,source)=>{let s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};this.program=gl.createProgram();gl.attachShader(this.program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(this.program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(this.program);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.program));const sv=`#version 300 es
precision highp float;layout(location=0) in vec3 pos;layout(location=2) in mat4 model;layout(location=6) in vec3 color;uniform mat4 vp;out vec2 uv;out float opacity;out vec3 wp;void main(){vec4 p=model*vec4(pos,1.);uv=pos.xz;opacity=color.x;wp=p.xyz;gl_Position=vp*p;}`;
 const sf=`#version 300 es
precision highp float;in vec2 uv;in float opacity;in vec3 wp;uniform vec3 eye;out vec4 outColor;void main(){float a=(1.-smoothstep(.18,1.,length(uv)))*opacity;float fog=smoothstep(45.,175.,distance(eye,wp));outColor=vec4(.13,.20,.20,a*(1.-fog*.7));}`;
 this.shadowProgram=gl.createProgram();gl.attachShader(this.shadowProgram,shader(gl.VERTEX_SHADER,sv));gl.attachShader(this.shadowProgram,shader(gl.FRAGMENT_SHADER,sf));gl.linkProgram(this.shadowProgram);if(!gl.getProgramParameter(this.shadowProgram,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.shadowProgram));this.shadowVP=gl.getUniformLocation(this.shadowProgram,'vp');this.shadowEye=gl.getUniformLocation(this.shadowProgram,'eye');this.shadows=this.makeBatch(shadowGeometry());this.poseCache=new WeakMap();
 this.vp=gl.getUniformLocation(this.program,'vp');this.eye=gl.getUniformLocation(this.program,'eye');this.batches=[this.makeBatch(geometry()),this.makeBatch(geometry(true))];this.colors=teamData.map(t=>t.color);this.parts=0;this.models=new Map([['stick',(u,b,c,s)=>this.humanoid(u,b,c,s)],['muscle',(u,b,c,s)=>this.humanoid(u,b,c,s)]]);this.contextLost=false;canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.contextLost=true});canvas.addEventListener('webglcontextrestored',()=>location.reload());}
 makeBatch(g){let gl=this.gl,vao=gl.createVertexArray(),geometryBuffers=[];gl.bindVertexArray(vao);for(let [loc,data] of [[0,g.positions],[1,g.normals]]){let b=gl.createBuffer();geometryBuffers.push(b);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);}let buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);for(let i=0;i<4;i++){gl.enableVertexAttribArray(2+i);gl.vertexAttribPointer(2+i,4,gl.FLOAT,false,76,i*16);gl.vertexAttribDivisor(2+i,1);}gl.enableVertexAttribArray(6);gl.vertexAttribPointer(6,3,gl.FLOAT,false,76,64);gl.vertexAttribDivisor(6,1);return {vao,buffer,geometryBuffers,vertices:g.count,array:new Float32Array(19*2048),n:0};}
 add(matrix,color,head=false){let b=this.batches[head?1:0],offset=b.n*19;if(offset+19>b.array.length){let a=new Float32Array(b.array.length*2);a.set(b.array);b.array=a;}b.array.set(matrix,offset);b.array.set(color,offset+16);b.n++;}
 box(x,y,z,sx,sy,sz,color,yaw=0,head=false){let c=Math.cos(yaw),s=Math.sin(yaw);this.add([c*sx,0,-s*sx,0,0,sy,0,0,s*sz,0,c*sz,0,x,y,z,1],color,head);}
 segment(a,b,r,color){let v=b.map((x,i)=>x-a[i]),length=Math.hypot(...v)||.001,y=norm(v),x=norm(cross(Math.abs(y[1])>.95?[1,0,0]:[0,1,0],y)),z=cross(x,y);this.add([x[0]*r,x[1]*r,x[2]*r,0,y[0]*length,y[1]*length,y[2]*length,0,z[0]*r,z[1]*r,z[2]*r,0,(a[0]+b[0])/2,(a[1]+b[1])/2,(a[2]+b[2])/2,1],color);}
 registerModel(name,builder){this.models.set(name,builder);}
 visualPose(u){let state=this.poseCache.get(u);if(!state){state={view:{...u},attack:{time:0},serial:u.visualHit||0,until:0};this.poseCache.set(u,state);}const v=state.view;v.hp=u.hp;v.flash=u.flash;v.command=u.command;v.controller=u.controller;const hit=state.serial!==(u.visualHit||0);if(hit){state.serial=u.visualHit||0;state.until=this.visualNow+55;}if(hit||this.visualNow>=state.until||v.x===undefined){for(const k of POSE_KEYS)v[k]=u[k];state.attack.time=u.attack?.time||0;v.attack=u.attack?state.attack:null;}return v;}
 unit(u,battle,camera,selected){const v=this.visualPose(u),builder=this.models.get(u.data.modelType)||this.models.get('stick');builder(v,battle,camera,selected===u?v:selected);if(u.hp>0||u.deadTime<1.5)this.blob(v,battle);if(u.flash>0&&this.hitMarks<this.hitLimit){this.hitMarks++;let y=v.y+1.15*u.data.size;for(let i=0;i<5;i++){let a=i/5*TAU,r=.28+(1-u.flash/.18)*.3;this.segment([v.x+Math.cos(a)*r,y+Math.sin(a)*r,v.z],[v.x+Math.cos(a)*(r+.23),y+Math.sin(a)*(r+.23),v.z+.08],.06,[1,.74,.12]);}}}
 blob(u,battle){const b=this.shadows,g=battle.terrain.heightAt(u.x,u.z),height=Math.max(0,u.y-g),radius=(u.data.modelType==='muscle'?.85:.48)*u.data.size*(1+height*.08),sx=(battle.terrain.heightAt(u.x+.3,u.z)-battle.terrain.heightAt(u.x-.3,u.z))/.6,sz=(battle.terrain.heightAt(u.x,u.z+.3)-battle.terrain.heightAt(u.x,u.z-.3))/.6;if(b.n*19+19>b.array.length){let a=new Float32Array(b.array.length*2);a.set(b.array);b.array=a;}b.array.set([radius,sx*radius,0,0,0,1,0,0,0,sz*radius,radius,0,u.x,g+.045,u.z,1,.34/(1+height*.35),0,0],b.n++*19);}

 humanoid(u,battle,camera,selected){let c=u.data,scale=c.size,color=u.flash>0?[1,1,1]:this.colors[u.team];let isDead=u.hp<=0;if(isDead&&u.deadTime>1.8)return;let far=Math.hypot(u.x-camera.eye[0],u.z-camera.eye[2])>65,lod=battle.count>1800||far;let walk=u.command.x||u.command.z?Math.sin(u.motion*9+u.id)*.32:0;let attack=u.attack?attackPose(u.attack.time,c.windup):0;let fall=isDead?Math.min(1,u.deadTime*3):u.stun>.4?.9:0;let cy=Math.cos(u.yaw),sy=Math.sin(u.yaw);
 const at=(x,y,z)=>{if(fall){let yy=y;y=y*(1-fall)+.2;z+=yy*fall;if(c.weapon==='water')x+=Math.sin(u.motion*12)*fall*.2;}return [u.x+(x*cy+z*sy)*scale,u.y+y*scale,u.z+(-x*sy+z*cy)*scale]};
 let muscle=c.modelType==='muscle',thickness=muscle?.38:.115,torso=muscle?.40:.15;let crooked=Math.sin(u.id*2.37)*.035;
 this.segment(at(0,.8,0),at(.03+crooked,1.5,0),torso,color);if(muscle){let chest=at(0,1.32,0);this.box(...chest,.58*scale,.45*scale,.32*scale,color,u.yaw,true);for(let side of [-1,1]){let shoulder=at(side*.28,1.45,0);this.box(...shoulder,.28*scale,.26*scale,.26*scale,color,u.yaw,true);}}let heads=c.heads||1;for(let i=0;i<heads;i++){let p=at((i-(heads-1)/2)*.32,1.8,0);this.box(...p,(muscle?.28:.23)*scale,(muscle?.30:.26)*scale,(muscle?.28:.23)*scale,color,u.yaw,true);}
 this.segment(at(-.06,.85,0),at(-.25-crooked,.12,walk),thickness,color);this.segment(at(.06,.85,0),at(.25+crooked,.12,-walk),thickness,color);
 const handL=at(-.40,1.12+attack*.4,.22+attack*.8),handR=at(.40,1.10+attack*.4,.20+attack*.8);this.segment(at(-.10,1.45,0),handL,thickness,color);this.segment(at(.10,1.45,0),handR,thickness,color);
 if(muscle){for(let h of [handL,handR])this.box(...h,.36*scale,.36*scale,.36*scale,color,u.yaw,true);}
 if(!lod||c.weapon!=='punch'){let n=Math.min(c.damage.length,5);if(c.weapon==='god'||c.weapon==='muscle')n=1;for(let i=0;i<n;i++){let h=i%2?handL:handR,w=c.weapon==='mixed'?(i?'sword':'hammer'):c.weapon;let metal=[.78,.85,.88],end=[h[0]+sy*.65,h[1]+.85+attack*.3,h[2]+cy*.65];if(w==='hammer'){let a=attack*1.35;end=[h[0]+sy*Math.sin(a)*1.05,h[1]+Math.cos(a)*1.05,h[2]+cy*Math.sin(a)*1.05];this.segment(h,end,.11,[.32,.22,.16]);this.box(...end,.8,.4,.4,metal,u.yaw);}else if(['sword','katana','god','spear','allSpear'].includes(w)){let length=w.includes('Spear')||w==='spear'?2.25:w==='katana'||w==='god'?1.9:1.35;let spear=w==='spear'||w==='allSpear',angle=u.yaw+(spear?0:attack*.8-.4),tip=[h[0]+Math.sin(angle)*length,h[1]+.18+(spear?attack*.1:0),h[2]+Math.cos(angle)*length];this.segment(h,tip,.12,metal);this.box(...tip,.16,.15,.32,metal,u.yaw,true);this.box(...h,.33,.10,.15,[.28,.21,.16],u.yaw);}else if(['water','fire'].includes(w))this.box(...h,.20,.20,.20,w==='water'?[.1,.9,1]:[1,.42,.06],0,true);}}
 if(c.immune){for(let i=0;i<8;i++){let a=i/8*TAU,p=at(Math.cos(a)*.42,2.25,Math.sin(a)*.42);this.box(...p,.18,.10,.18,[1,.74,.12],u.yaw,true);}let p=at(0,2.68,0);this.box(...p,.18,.28,.18,[1,.74,.12],u.yaw,true);}
 if(c.weapon==='katana'){let p=at(0,1.88,0);this.box(...p,.60*scale,.10*scale,.3*scale,[.2,.15,.25],u.yaw);p=at(0,2.30,0);this.box(...p,.16,.25,.16,[.65,.25,.85],u.yaw,true);}
 if(c.weapon==='allSpear'){for(let i=-1;i<=1;i++)this.segment(at(i*.22,.8,-.18),at(i*.48,2.5,-.3),.10,[.83,.64,.12]);}
if(u===selected)this.box(u.x,battle.terrain.heightAt(u.x,u.z)+.035,u.z,1.8,.05,1.8,[1,.85,.2]);
 }
 terrainMesh(terrain){if(this.surfaceTerrain===terrain)return;this.surfaceTerrain=terrain;let positions=[],normals=[];for(let x=-50;x<50;x+=2)for(let z=-35;z<35;z+=2){const a=[x,terrain.heightAt(x,z)+.018,z],b=[x+2,terrain.heightAt(x+2,z)+.018,z],c=[x+2,terrain.heightAt(x+2,z+2)+.018,z+2],d=[x,terrain.heightAt(x,z+2)+.018,z+2];for(const tri of [[a,c,b],[a,d,c]]){let n=norm(cross(tri[1].map((v,i)=>v-tri[0][i]),tri[2].map((v,i)=>v-tri[0][i])));for(const v of tri){positions.push(...v);normals.push(...n);}}}if(this.surface){this.gl.deleteVertexArray(this.surface.vao);this.gl.deleteBuffer(this.surface.buffer);for(const b of this.surface.geometryBuffers||[])this.gl.deleteBuffer(b);}this.surface=this.makeBatch({positions:new Float32Array(positions),normals:new Float32Array(normals),count:positions.length/3});this.surface.array.set([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,.54,.65,.43]);this.surface.n=1;}
 draw(battle,camera,selected,marker=null,selectionIds=null){if(this.contextLost)return;let gl=this.gl,r=this.canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,battle&&battle.count>1000?1:1.5);let w=Math.round(r.width*ratio),h=Math.round(r.height*ratio);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}camera.update(r.width/r.height);this.visualNow=performance.now();this.hitMarks=0;this.hitLimit=battle?.count>400?16:32;this.shadows.n=0;this.batches.forEach(b=>b.n=0);
 this.box(0,-.16,0,102,.3,72,[.56,.67,.46]);if(battle?.terrain.hills.length)this.terrainMesh(battle.terrain);else this.surfaceTerrain=null;for(let x=-50;x<=50;x+=10)this.box(x,.004,0,.055,.01,70,[.51,.62,.42]);for(let z=-35;z<=35;z+=10)this.box(0,.004,z,100,.01,.055,[.51,.62,.42]);for(let z of [-22,0,22]){this.box(-48,.1,z,1,.2,5,this.colors[0]);this.box(48,.1,z,1,.2,5,this.colors[1]);}
 // Sparse, fixed sketch strokes: no textures, no per-frame random allocation.
 for(let i=0;i<38;i++){let x=Math.sin(i*7.17)*47,z=Math.cos(i*3.13)*32,y=(battle?.terrain.heightAt(x,z)||0)+.035;this.box(x,y,z,.65,.015,.055,[.39,.52,.32],i*.71);this.box(x+.35,y,z+.15,.32,.015,.04,[.44,.57,.35],i*.71+.4);}
 if(marker?.points){const color=marker.invalid?[1,.2,.2]:marker.selectionPreview?[1,.82,.15]:this.colors[marker.team].map(v=>.45+v*.55);for(const p of marker.points){const y=battle.terrain.heightAt(p.x,p.z)+.07,r=characterRadius(p.type);this.box(p.x,y,p.z,r*2,.035,r*2,color);}}
 if(marker){let color=marker.invalid?[1,.2,.2]:marker.color||this.colors[marker.team];for(let i=0;i<16;i++){let a=i/16*TAU;this.box(marker.x+Math.cos(a)*(marker.radius||.75),(battle?.terrain.heightAt(marker.x,marker.z)||0)+.06,marker.z+Math.sin(a)*(marker.radius||.75),.12,.08,.12,color);}this.box(marker.x,(battle?.terrain.heightAt(marker.x,marker.z)||0)+.06,marker.z,.2,.08,.2,color);}
 if(battle){for(const o of battle.terrain.objects){const d=terrainData[o.type],s=o.scale||1,y=battle.terrain.heightAt(o.x,o.z),color=selected?.objectId===o.id?[1,.85,.2]:d.color.match(/\w\w/g).map(v=>parseInt(v,16)/255);if(o.type==='rock')this.box(o.x,y+d.height*s/2,o.z,d.radius*s,d.height*s/2,d.radius*s,color,o.yaw,true);else if(o.type==='wall')this.box(o.x,y+d.height*s/2,o.z,d.width*s,d.height*s,d.depth*s,color,o.yaw);}
 for(let u of battle.units){let p=camera.project(u.x,u.y+1,u.z,r.width,r.height);if(!p||p[0]<-120||p[0]>r.width+120||p[1]<-120||p[1]>r.height+120)continue;this.unit(u,battle,camera,selected);
 if(selectionIds?.has(u.id)){const y=battle.terrain.heightAt(u.x,u.z)+.09,r=Math.max(.65,u.data.radius+.25),gold=[1,.78,.07];for(const sign of [-1,1]){this.box(u.x+sign*r,y,u.z,.10,.06,2*r,gold);this.box(u.x,y,u.z+sign*r,2*r,.06,.10,gold);}this.box(u.x,u.y+2.65*u.data.size,u.z,.23,.32,.23,gold,0,true);}}
 for(let p of battle.projectiles.slice(0,180)){if(p.time<0)continue;let f=Math.min(1,p.time/p.duration),x=p.sx+(p.tx-p.sx)*f,z=p.sz+(p.tz-p.sz)*f,y=(p.sy||1.1)+((p.ty||1.1)-(p.sy||1.1))*f+Math.sin(f*Math.PI)*2;let color=p.kind==='water'?[.1,.8,1]:p.kind==='fire'?[1,.4,.03]:[.92,.88,.7];if(p.kind==='dumbbell'){y=18*(1-f)+.7+battle.terrain.heightAt(p.tx,p.tz);this.box(x,y,z,3,.5,.5,[.6,.65,.72]);this.box(x-1.4,y,z,.7,1.8,1.8,[.75,.8,.87]);this.box(x+1.4,y,z,.7,1.8,1.8,[.75,.8,.87]);}else if(p.kind==='spear'){let dx=p.tx-p.sx,dz=p.tz-p.sz,l=Math.hypot(dx,dz)||1;this.segment([x,y,z],[x+dx/l*1.6,y,z+dz/l*1.6],.07,color);}else this.box(x,y,z,p.area?.9:.3,p.area?.9:.3,p.area?.9:.3,color,0,true);}
 for(let e of battle.effects){let ground=battle.terrain.heightAt(e.x,e.z),f=e.time/e.duration,col=e.kind==='heal'?[.25,1,.45]:e.kind==='shock'?[1,.65,.2]:e.kind==='water'?[.15,.85,1]:e.kind==='fire'?[1,.4,.02]:[1,.85,.3];if(e.kind==='lightning'||e.kind==='divineLightning'){const divine=e.kind==='divineLightning',n=divine?1:5;for(let i=0;i<n;i++){let x=e.x+(i-(n-1)/2)*3;this.segment([x,ground+20,e.z],[x+.8,ground+9,e.z-.8],.16,col);this.segment([x+.8,ground+9,e.z-.8],[x,ground+.1,e.z],.16,col);}}
 else if(e.kind==='allSpear'){for(let i=0;i<30;i++){let x=e.x+Math.sin(i)*i*.4,z=e.z+Math.cos(i)*i*.4;this.segment([x,2,z],[x+(e.team?-1:1)*f*15,1,z+.4],.04,col);}}
 else{let count=e.kind==='water'?5:12;for(let i=0;i<count;i++){let a=i/count*TAU,r=e.radius*f;this.box(e.x+Math.cos(a)*r,ground+.4+Math.sin(f*Math.PI)*2,e.z+Math.sin(a)*r,.16,.16,.16,col,0,true);}}}}
 gl.viewport(0,0,w,h);gl.clearColor(.75,.86,.88,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.useProgram(this.program);gl.uniformMatrix4fv(this.vp,false,camera.matrix);gl.uniform3fv(this.eye,camera.eye);this.parts=0;this.drawCalls=0;for(let b of [...this.batches,...(battle?.terrain.hills.length&&this.surface?[this.surface]:[])]){gl.bindVertexArray(b.vao);gl.bindBuffer(gl.ARRAY_BUFFER,b.buffer);gl.bufferData(gl.ARRAY_BUFFER,b.array.subarray(0,b.n*19),gl.DYNAMIC_DRAW);gl.drawArraysInstanced(gl.TRIANGLES,0,b.vertices,b.n);this.drawCalls++;this.parts+=b.n;}
 // One instanced transparent pass for every visible shadow; no shadow maps.
 const b=this.shadows;if(b.n){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.useProgram(this.shadowProgram);gl.uniformMatrix4fv(this.shadowVP,false,camera.matrix);gl.uniform3fv(this.shadowEye,camera.eye);gl.bindVertexArray(b.vao);gl.bindBuffer(gl.ARRAY_BUFFER,b.buffer);gl.bufferData(gl.ARRAY_BUFFER,b.array.subarray(0,b.n*19),gl.DYNAMIC_DRAW);gl.drawArraysInstanced(gl.TRIANGLES,0,b.vertices,b.n);this.drawCalls++;this.parts+=b.n;gl.depthMask(true);gl.disable(gl.BLEND);}}

}
