import fs from 'node:fs';
globalThis.localStorage={data:new Map(),getItem(k){return this.data.get(k)??null},setItem(k,v){this.data.set(k,v)}};
const results=await (async()=>{
 const {Battle}=await import('../simulation.js'),{characterData}=await import('../data.js'),{FieldEditor}=await import('../editor.js');let checks=[],bench=[];
 function ok(v,label){if(!v)throw Error(label);checks.push(label);}
 const config=(n,teams=2)=>Array.from({length:teams},()=>characterData.map((_,i)=>i===0?n:0));
 const stage=(units,multipliers,terrain=[])=>({units:units.map((u,id)=>({id,team:u[0],type:u[1],x:u[2],z:u[3],yaw:0})),terrain,multipliers});
 let b=new Battle(config(1));ok(b.alive.join()==='1,1,0,0','legacy two-team config');b.units[1].receiveDamage(100,b.units[0],'punch',b);ok(b.result==='TEAM A WIN','two-team winner');
 b=new Battle([],stage([[0,0,-2,0],[1,0,0,0],[2,0,2,0],[3,0,4,0]]));b.units[1].receiveDamage(100,b.units[0],'punch',b);ok(!b.result,'B eliminated: C/D continue');b.units[0].receiveDamage(100,b.units[2],'punch',b);ok(!b.result,'A/B eliminated: C/D continue');b.units[3].receiveDamage(100,b.units[2],'punch',b);ok(b.result==='TEAM C WIN','C wins');
 for(const type of [15,16,17]){b=new Battle([],stage([[0,type,-2,0],[0,0,-3,0],[1,0,0,0],[2,0,2,0],[3,0,4,0]]));b.resolve(b.units[0],b.units[2],[30],'katana',0,true,0,0);ok(b.units.slice(2).every(u=>u.hp===70)&&b.units[1].hp===100,'global attack across three enemy teams type '+type);}
 let mult=[{hp:2,attack:3,speed:2}];b=new Battle([],stage([[0,0,0,0],[1,0,1,0]],mult));let u=b.units[0],v=b.units[1];ok(u.maxHp===200&&u.hp===200,'HP multiplier');b.performAttack(u,v);ok(v.hp===70,'melee attack multiplier');u.command={x:1,z:0,target:null,attack:false};u.update(.1,b);ok(Math.abs(u.x-.56)<1e-6,'speed multiplier');let added=b.addCharacter(0,0,-10,0);ok(added.hp===200&&added.multipliers.attack===3,'reinforcement inherits multipliers');ok(b.addCharacter(3,0,10,0)?.team===3,'D enters ongoing battle');ok(!b.addCharacter(4,0,0,0),'invalid team rejected');
 b=new Battle([],stage([[0,15,0,0],[1,0,1,0],[2,0,2,0],[3,0,3,0]],mult));b.performAttack(b.units[0],b.units[1]);b.step(2);ok(b.units.slice(1).every(u=>u.hp===0),'all-spear projectile multiplier');
 const giant=characterData.findIndex(c=>c.name==='ギガント');b=new Battle([],stage([[0,giant,0,0],[0,0,0,2],[1,0,2,0],[2,0,0,-2],[3,0,20,0]]));ok(b.units[0].hp===3000&&b.units[0].data.size===3.6,'gigant stats and size');b.performAttack(b.units[0],b.units[2]);ok(b.units[1].hp===100&&b.units[2].hp===0&&b.units[3].hp===0&&b.units[4].hp===100,'gigant area attack: no friendly fire/outside range');
 const ed=new FieldEditor(stage([[0,0,-20,0],[3,giant,20,0]],mult));ed.placeTerrain('wall',0,0);let tid=ed.stage.terrain[0].id;ed.rotate('terrain',tid);ed.move('terrain',tid,0,10);ed.undo();ok(ed.stage.terrain[0].z===0,'terrain move/rotate/undo');ed.save('phase1-test');let loaded=new FieldEditor();loaded.load('phase1-test');ok(loaded.stage.units[1].team===3&&loaded.stage.multipliers[0].hp===2&&loaded.stage.terrain.length===1,'save/load four teams, gigant, terrain, multipliers');ed.clear('all');ok(ed.stage.multipliers[0].hp===2,'clear preserves settings');ed.undo();ok(ed.stage.units.length===2,'clear undo');localStorage.setItem('stick-fight-presets-v1',JSON.stringify([{name:'legacy',version:1,stage:stage([[0,0,-5,0],[1,0,5,0]])}]));loaded.load('legacy');ok(loaded.stage.multipliers.every(m=>m.hp===1),'legacy preset defaults');
 for(const n of [50,100,300]){let timings=[];b=new Battle(config(n));const start=performance.now();for(let i=0;i<1800&&!b.result;i++){let st=performance.now();b.step(1/30);timings.push(performance.now()-st);}timings.sort((a,b)=>a-b);ok(b.events>0&&b.units.every(u=>[u.x,u.z,u.hp].every(Number.isFinite)),n+'vs'+n+' finite simulation and combat');for(let t=0;t<4;t++){ok(Math.abs(b.hp[t]-b.teams[t].reduce((s,u)=>s+Math.max(0,u.hp),0))<1e-6,n+'vs'+n+' HP bookkeeping team '+t);}bench.push({scenario:n+'vs'+n,simulatedSeconds:b.time,meanMs:timings.reduce((a,b)=>a+b,0)/timings.length,p95Ms:timings[Math.floor(timings.length*.95)],elapsedMs:performance.now()-start,attacks:b.events});}
 b=new Battle(config(150,4));for(let i=0;i<900&&!b.result;i++)b.step(1/30);ok(b.events>0&&b.units.every(u=>Number.isFinite(u.hp)),'four-way 150 each combat');
 return {checks,bench};
})();fs.writeFileSync('simulation-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));