/** Actual game-v12.js pointer handlers with a small DOM/WebGL adapter, not a browser test. */
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),checks=[];const ok=(v,s)=>{assert(v,s);checks.push(s)};
export async function environment(width=1000,height=650){const ids=new Map(),all=[],listeners=new Map();let serial=0;
 class Element{constructor(tag='div',attributes={}){this.tagName=tag.toUpperCase();this.attributes={};this.children=[];this.style={};this.dataset={};this.hidden=false;this.disabled=false;this._value='';this._text='';this.classList={add(){},remove(){},toggle(){}};this.listeners=new Map();all.push(this);for(const [k,v] of Object.entries(attributes))this.setAttribute(k,v);}
 set id(v){this.attributes.id=v;ids.set(v,this);}get id(){return this.attributes.id||'';}set value(v){this._value=String(v)}get value(){if(this.tagName==='SELECT'&&!this._value)return this.children.find(c=>c.attributes.selected!==undefined)?.value||this.children[0]?.value||'';return this._value;}
 get options(){return this.children}get selectedOptions(){return this.children.filter(c=>c.value===this.value).slice(0,1)}set textContent(t){this._text=String(t)}get textContent(){return this._text||this.children.map(c=>c.textContent).join('')}
 set innerHTML(html){this.children=[];parse(html,this);}get innerHTML(){return '';}
 setAttribute(k,v){this.attributes[k]=String(v);if(k==='id'){ids.set(String(v),this);}if(k==='value')this._value=String(v);if(k==='hidden')this.hidden=true;if(k==='disabled')this.disabled=true;if(k.startsWith('data-'))this.dataset[k.slice(5)]=String(v)}getAttribute(k){return this.attributes[k]??null;}
 append(...els){for(const el of els){if(el.parentElement)el.parentElement.children=el.parentElement.children.filter(e=>e!==el);this.children.push(el);el.parentElement=this;}}prepend(...els){this.append(...els)}after(){}replaceChildren(...els){this.children=[];this.append(...els)}closest(){return this.parentElement||new Element('label')}
 querySelector(q){return q==='small'?this.children.find(c=>c.tagName==='SMALL'):new Element(q)}addEventListener(name,fn){if(!this.listeners.has(name))this.listeners.set(name,[]);this.listeners.get(name).push(fn)}getBoundingClientRect(){return {left:0,top:0,right:width,bottom:height,width,height}}setPointerCapture(){}
 getContext(){return new Proxy({}, {get:(_,k)=>k==='getShaderParameter'||k==='getProgramParameter'?()=>true:k==='getUniformLocation'||String(k).startsWith('create')?()=>({id:serial++}):String(k).toUpperCase()===k?serial++:()=>{}})}
 }
 function attrs(s){const a={};for(const m of s.matchAll(/([\w-]+)(?:="([^"]*)")?/g))a[m[1]]=m[2]??'';return a;}
 function parse(html,parent){const re=/<(input|select|option|button|span|small|b|div|canvas|progress|section|strong|p|label|details|output|h2|h3|tbody)\b([^>]*)>([^<]*)/g;for(const m of html.matchAll(re)){const a=attrs(m[2]);if(!a.id&&m[1]!=='option'&&!a['data-tool']&&!a['data-team'])continue;const el=new Element(m[1],a);el.textContent=m[3];parent?.append(el);if(m[1]==='select'){const end=html.indexOf('</select>',m.index);el.innerHTML=html.slice(m.index+m[0].length,end);}}
 }
 parse(fs.readFileSync(path.join(root,'index.html'),'utf8'));const named=new Map();for(const q of ['.hud','.controls','.placement'])named.set(q,new Element('div'));
 const document={body:new Element('body'),getElementById:id=>ids.get(id),createElement:t=>new Element(t),querySelector:q=>named.get(q)||ids.get(q.replace(/^#/,'')),querySelectorAll:q=>q==='.row input'?all.filter(el=>/^n\d_\d+$/.test(el.id)):q==='#editModeButtons button'?all.filter(el=>el.dataset.tool):q==='#selectTeams button'?all.filter(el=>el.dataset.team):[]};
 const window={addEventListener:(k,fn)=>{if(!listeners.has(k))listeners.set(k,[]);listeners.get(k).push(fn)}};const storage=new Map();const context=vm.createContext({document,window,navigator:{},location:{protocol:'http:',reload(){}},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},requestAnimationFrame(){},devicePixelRatio:1,performance,console,queueMicrotask,confirm:()=>true,setTimeout,clearTimeout});
 const cache=new Map();const make=file=>{if(cache.has(file))return cache.get(file);let source=fs.readFileSync(file,'utf8');if(file.endsWith('/game-v12.js'))source+=`\nexport const testing={get editor(){return editor},get battle(){return battle},get selection(){return unitSelection},get camera(){return camera},get marker(){return marker},get renderer(){return renderer},get pointers(){return pointers},get gesture(){return selectionGesture},chooseMode,get mode(){return currentMode},openEditor,beginBattle,refreshEditor,selectMode,frame,groupScreen};`;const mod=new vm.SourceTextModule(source,{context,identifier:file});cache.set(file,mod);return mod;};const game=make(path.join(root,'game-v12.js'));await game.link((specifier,referencer)=>make(path.resolve(path.dirname(referencer.identifier),specifier)));await game.evaluate();const api=game.namespace.testing;assert(api.editor,ids.get('notice')?.textContent);const canvas=ids.get('canvas');
 const event=(pointerId,x,y,extra={})=>({pointerId,pointerType:width<600?'touch':'mouse',clientX:x,clientY:y,button:0,preventDefault(){},target:canvas,...extra});const send=(kind,id,p,extra={})=>canvas['onpointer'+kind](event(id,p[0],p[1],extra));const drag=(a,b,extra={})=>{send('down',1,a,extra);for(let i=1;i<=5;i++)send('move',1,[a[0]+(b[0]-a[0])*i/5,a[1]+(b[1]-a[1])*i/5],extra);send('up',1,b,extra)};const tap=(p,extra={})=>{send('down',1,p,extra);send('up',1,p,extra)};
 const project=(u,y=1.3)=>{api.camera.update(width/height);return api.camera.project(u.x,api.battle.terrain.heightAt(u.x,u.z)+y,u.z,width,height)};
 return {api,ids,all,canvas,listeners,send,drag,tap,project,width,height};}
